// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "uslbar.h"

/////////////////////////////////////////////////////////////////////////////
// CUSLBar

IMPLEMENT_DYNCREATE(CUSLBar, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CUSLBar properties

long CUSLBar::GetWidthLowCursor()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetWidthLowCursor(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CUSLBar::GetWidthHighCursor()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetWidthHighCursor(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CUSLBar::GetWidthControl()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetWidthControl(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CUSLBar::GetLowPosition()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetLowPosition(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CUSLBar::GetHighPosition()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetHighPosition(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CUSLBar::GetHorizontal()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetHorizontal(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

long CUSLBar::GetMax()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetMax(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

long CUSLBar::GetMin()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetMin(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

long CUSLBar::GetWidth()
{
	long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetWidth(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

long CUSLBar::GetMinimumScreenWidth()
{
	long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CUSLBar::SetMinimumScreenWidth(long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CUSLBar operations

void CUSLBar::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
