#if !defined(AFX_USLBAR_H__9B54638F_8443_4E67_8E65_F3691767DC01__INCLUDED_)
#define AFX_USLBAR_H__9B54638F_8443_4E67_8E65_F3691767DC01__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CUSLBar wrapper class

class CUSLBar : public CWnd
{
protected:
	DECLARE_DYNCREATE(CUSLBar)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x76b1d74d, 0xcb4, 0x11d4, { 0xae, 0xdb, 0x80, 0x10, 0x50, 0xc1, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetWidthLowCursor();
	void SetWidthLowCursor(long);
	long GetWidthHighCursor();
	void SetWidthHighCursor(long);
	long GetWidthControl();
	void SetWidthControl(long);
	long GetLowPosition();
	void SetLowPosition(long);
	long GetHighPosition();
	void SetHighPosition(long);
	long GetHorizontal();
	void SetHorizontal(long);
	long GetMax();
	void SetMax(long);
	long GetMin();
	void SetMin(long);
	long GetWidth();
	void SetWidth(long);
	long GetMinimumScreenWidth();
	void SetMinimumScreenWidth(long);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_USLBAR_H__9B54638F_8443_4E67_8E65_F3691767DC01__INCLUDED_)
