//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OEMPATool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ExampleCscanDisTYPE         129
#define IDD_DIALOG_HW                   130
#define IDD_DIALOG_SETUPFILES           132
#define IDD_DIALOG_HW_LINK              135
#define IDD_DIALOG_CSCAN_DISPLAY        138
#define IDD_DIALOG_KERNELMESSAGEBOX     140
#define IDD_DIALOG_MAXIMUM              141
#define IDD_DIALOG_CALIBRATION          142
#define IDD_DIALOG_TEST_FW_MEMORY       143
#define IDD_DIALOG1                     144
#define IDC_BUTTON_CREATE               1000
#define IDC_BUTTON_REGISTRATION         1000
#define IDC_EDIT_DISPLAY_ACQUISITION_DATA_ID 1001
#define IDC_BUTTON_REGISTRATION2        1001
#define IDC_BUTTON_ASCAN                1001
#define IDC_BUTTON_SYSTEM_NEW           1001
#define IDC_BUTTON_DISPLAY              1002
#define IDC_BUTTON_FILE_OEMPA_SAMPLE    1002
#define IDC_BUTTON_SYSTEM_LOAD          1002
#define IDC_BUTTON_FILE_SAMPLE_BASIC    1002
#define IDC_BUTTON_UPDATE               1003
#define IDC_BUTTON_FILLDATATEST_CALL    1003
#define IDC_BUTTON_FILE_OEMPA_LOAD      1003
#define IDC_EDIT_SYSTEM                 1003
#define IDC_BUTTON_FILE_SAMPLE_BASIC2   1003
#define IDC_BUTTON_FILE_SAMPLE          1003
#define IDC_EDIT_TESTPATTERN            1004
#define IDC_BUTTON_FILE_OEMPA_SAVE      1004
#define IDC_BUTTON_WIZARD_DELETE        1004
#define IDC_BUTTON_FILE_OPTION          1004
#define IDC_EDIT_SYSTEM2                1004
#define IDC_EDIT_MATCHED_DEVICE         1004
#define IDC_CHECK_CALLBACK_ON_AXIS      1005
#define IDC_BUTTON_FILE_TXT_TO_BIN      1005
#define IDC_BUTTON_SYSTEM_SAVE          1005
#define IDC_BUTTON_CONFIG               1005
#define IDC_EDIT_GAIN                   1006
#define IDC_BUTTON_WIZARD_UPDATE        1006
#define IDC_EDIT_QTY                    1007
#define IDC_BUTTON_FILE_SAMPLE_WIZARD   1007
#define IDC_BUTTON_FILE_TXT_TO_BIN2     1007
#define IDC_BUTTON_TXT_TO_BIN           1007
#define IDC_BUTTON_FILE_OEMPA_LOAD2     1007
#define IDC_EDIT_A                      1008
#define IDC_EDIT_AMP_QTY                1008
#define IDC_BUTTON_FILE_SAMPLE_WIZARD2  1008
#define IDC_BUTTON_WIZARD_TO_HW         1008
#define IDC_BUTTON_WIZARD_TO_FILE       1008
#define IDC_BUTTON_WRITE                1009
#define IDC_BUTTON_WIZARD_SAVE          1009
#define IDC_BUTTON_WIZARD_TO_FILE2      1009
#define IDC_CHECK_HISTORIC_WRITE        1010
#define IDC_EDIT_GAIN2                  1010
#define IDC_EDIT_ERROR                  1010
#define IDC_BUTTON_AXIS_START_WRITE     1011
#define IDC_BUTTON_FILE_BIN_TO_TXT      1011
#define IDC_BUTTON_SYSTEM_EDIT          1011
#define IDC_BUTTON_BIN_TO_TXT           1011
#define IDC_BUTTON_USB3_RESET           1011
#define IDC_BUTTON_FILE_OEMPA_LOAD3     1011
#define IDC_BUTTON_RESET_USB3           1011
#define IDC_EDIT_AXIS_START_READ        1012
#define IDC_BUTTON_FILE_BIN_DIFF        1012
#define IDC_CHECK_HISTORIC_READ         1013
#define IDC_CHECK_DISPLAY_TIMER         1013
#define IDC_EDIT_WIZARD                 1013
#define IDC_CHECK_SHOT_ENABLE           1013
#define IDC_BUTTON1                     1014
#define IDC_BUTTON_WIZARD_SYSTEM        1014
#define IDC_BUTTON_WIZARD_SYSTEM_CREATE 1014
#define IDC_CHECK_DISPLAY_TIMER2        1014
#define IDC_CHECK_CONNECTION_CALLBACK   1014
#define IDC_BUTTON_DESELECT             1014
#define IDC_BUTTON_DELETE               1014
#define IDC_BUTTON_CALIBRATION_RESET    1014
#define IDC_BUTTON_CYCLE                1014
#define IDC_EDIT_AXIS_START_WRITE       1015
#define IDC_CHECK_FIFO                  1015
#define IDC_CHECK_DISPLAY_BSCAN         1015
#define IDC_CHECK_DISPLAY_IMAGE         1015
#define IDC_BUTTON_CALIBRATION_PERFORM  1015
#define IDC_BUTTON_FILTER               1015
#define IDC_CHECK1                      1016
#define IDC_CHECK_WIZARD_SYSTEM_REGISTER 1016
#define IDC_CHECK_CONNECT               1016
#define IDC_CHECK_WIZARD_ENABLE2        1016
#define IDC_CHECK_WIZARD_ENABLE         1016
#define IDC_CHECK_ENABLE                1016
#define IDC_CHECK_MATCHED_DEVICE        1016
#define IDC_BUTTON_CALIBRATION_RESET2   1016
#define IDC_BUTTON_CHECK                1016
#define IDC_CHECK_CHANNEL_1             1016
#define IDC_IPADDRESS                   1017
#define IDC_CHECK_ENABLE_IMAGE          1017
#define IDC_CHECK_DISPLAY               1017
#define IDC_CHECK_CHANNEL_2             1017
#define IDC_CHECK_MATCHED_DEVICE_256    1017
#define IDC_EDIT1                       1018
#define IDC_EDIT_PORT                   1018
#define IDC_EDIT_MASTER_COUNT           1018
#define IDC_EDIT_OUT                    1018
#define IDC_CHECK_CHANNEL_3             1018
#define IDC_CHECK_FIFO2                 1019
#define IDC_CHECK_STANDBY               1019
#define IDC_BUTTON_WIZARD_VIEW          1019
#define IDC_CHECK_DISPLAY_INVERT        1019
#define IDC_EDIT_AXIS_OFFSET            1019
#define IDC_CHECK_CHANNEL_4             1019
#define IDC_CHECK_CALLBACK_ON_FREQUENCY 1020
#define IDC_CHECK_DISPLAY_TIMER3        1020
#define IDC_CHECK_DISPLAY_GRID          1020
#define IDC_BUTTON_RESET                1020
#define IDC_EDIT_AXIS_START             1020
#define IDC_CHECK_CHANNEL_5             1020
#define IDC_BUTTON_SPECIMEN_VELOCITYL_READ 1021
#define IDC_BUTTON_FREQUENCY_READ       1021
#define IDC_BUTTON_DISPLAY_GRID         1021
#define IDC_BUTTON_STATUS               1021
#define IDC_EDIT_GATE_START             1021
#define IDC_CHECK_CHANNEL_6             1021
#define IDC_EDIT_FREQUENCY_READ         1022
#define IDC_RADIO_ETHERNET              1022
#define IDC_EDIT_GATE_STOP              1022
#define IDC_CHECK_CHANNEL_7             1022
#define IDC_EDIT_FREQUENCY_WRITE        1023
#define IDC_RADIO_USB                   1023
#define IDC_EDIT_AXIS_STOP              1023
#define IDC_CHECK_CHANNEL_8             1023
#define IDC_COMBO_USB                   1024
#define IDC_EDIT_CYCLE                  1024
#define IDC_CHECK_CHANNEL_9             1024
#define IDC_SPIN_GAIN                   1025
#define IDC_CHECK_ENABLE_IMAGE2         1025
#define IDC_CHECK_ENABLE_HW             1025
#define IDC_CHECK_ENABLE_CSCAN          1025
#define IDC_EDIT_DATA                   1025
#define IDC_CHECK_TRANSMISSION_34       1025
#define IDC_COMBO_AMP                   1026
#define IDC_BUTTON_DISPLAY_COLOR        1026
#define IDC_CHECK_TRANSMISSION_56       1026
#define IDC_COMBO_AMP2                  1027
#define IDC_COMBO_DISPLAY_CYCLE         1027
#define IDC_CHECK_TRANSMISSION_78       1027
#define IDC_EDIT2                       1028
#define IDC_EDIT_ENCODER                1028
#define IDC_EDIT_POINT_COUNT            1028
#define IDC_EDIT_PORT3                  1028
#define IDC_BUTTON_FILE_SAMPLE_LINEAR   1029
#define IDC_CHECK_DISPLAY_INVERT2       1029
#define IDC_BUTTON_SCAN_LINEAR          1029
#define IDC_CHECK_DISPLAY_MAX           1029
#define IDC_COMBO1                      1029
#define IDC_COMBO_DEFAULT_LINK          1029
#define IDC_COMBO_GATE                  1029
#define IDC_BUTTON_FILE_SAMPLE_SECTORIAL 1030
#define IDC_BUTTON_SCAN_SECTORIAL       1030
#define IDC_COMBO_CHANNEL               1030
#define IDC_BUTTON_TOOLBOX              1031
#define IDC_STATIC_CHANNEL              1031
#define IDC_BUTTON_NOTEPAD              1032
#define IDC_EDIT_PORT2                  1032
#define IDC_EDIT_DATA_LOST              1032
#define IDC_LIST_BOARD                  1032
#define IDC_STATIC_CHANNEL2             1033
#define IDC_LIST_BOARD2                 1033
#define IDC_LIST_DEVICE                 1033
#define IDC_BUTTON_MULTI                1034
#define IDC_LIST_MESSAGE                1034
#define IDC_BUTTON_IO                   1035
#define IDC_BUTTON_OUTPUT               1035
#define IDC_RADIO_HW                    1035
#define IDC_RADIO_HW2                   1036
#define IDC_RADIO_SW                    1036
#define IDC_BUTTON_RESET2               1036
#define IDC_BUTTON_CALIBRATION          1036
#define IDC_STATIC_GAIN_UNIT            1037
#define IDC_STATIC_CYCLE                1038
#define IDC_CHECK_CALIBRATION_ENABLE    1039
#define IDC_CHECK_FMC_CALIBRATION       1040
#define IDC_CHECK_CALIBRATION_OFFSET    1040
#define IDC_RADIO1                      1041
#define IDC_RADIO_BUFFER_MAX            1041
#define IDC_RADIO_PULSE_ECHO            1041
#define IDC_RICHEDIT_ENCODER            1042
#define IDC_RADIO_TRANSMISSION          1042
#define IDC_STATIC_ALIGNMENT            1043
#define IDC_STATIC_OFFSET               1044
#define IDC_CHECK2                      1045
#define IDC_CHECK_TEST                  1045
#define IDC_CHECK_USB3_SIMULATOR        1046
#define IDC_CHECK_FILE_ADD_DATA_FORMAT  1047
#define IDC_CHECK_OEMPA_ASCAN_BITSIZE4  1054
#define IDC_CHECK_OEMPA_TRIGGER_MODE4   1055
#define ID_EDIT_DISPLAYACQDATA          32771
#define ID_EDIT_WIZARDDIALOG            32773
#define ID_EDIT_DIALOG_SETTING          32774
#define ID_EDIT_DIALOG_HARDWARE         32775
#define ID_EDIT_SETUPFILES              32776
#define ID_EDIT_MAXDIALOG               32777
#define ID_EDIT_MESSAGEBOX              32778
#define ID_EDIT_KERNELMESSAGEBOX        32779
#define ID_EDIT_TESTFWMEMORY            32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
