//HERE ARE COMPILATION CONSTANT WITH WHICH THE KERNEL HAVE BEEN COMPILED,
//THE USER CANNOT CHANGE THEM AFTER COMPILATION.
#pragma once

const char KIT_VERSION_LETTER='n';
const char KIT_CONFIGURATION[]="Release";
const char KIT_MANUFACTURER[]="AOS";

#define cKIT_PRODUCT		"OEMPA"
#define KIT_PRODUCT			L"OEMPA"

//#define _EVALUATION_
#ifdef _EVALUATION_
	#define EVALUATION_VALID_DAY_COUNT		1000
#endif _EVALUATION_
