//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PlateScanner.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TIMESLOT_DIALOG             102
#define IDD_GPD_DIALOG                  103
#define IDD_TIMS_DIALOG                 104
#define IDD_DIALOG_LIST_EDIT            105
#define IDD_LOGON_DIALOG                106
#define IDD_OPERATORS_DIALOG            107
#define IDD_SCAN_DIALOG                 108
#define IDD_DEVICE_RESOURCES_DIALOG     109
#define IDD_GENERAL_DIALOG              110
#define IDD_AXIS_PMAC_DIALOG            111
#define IDD_DIALOG_PMAC                 112
#define IDD_I_VARIABLES_DIALOG          113
#define IDD_AXES_STATUS_DIALOG          116
#define IDD_CARDS_DIALOG                117
#define IDD_SCOPE_DIALOG1               118
#define IDD_ADC200_DIALOG               119
#define IDD_SCOPE_OPTIONS_DIALOG        120
#define IDD_PRINT_DIALOG                121
#define IDD_PRINT_DIALOG1               122
#define IDD_NOTES_DIALOG                123
#define IDD_DIALOG_DATA_BASE            124
#define IDD_VIEW_MANIP_DIALOG           125
#define IDD_SERIAL_JOYSTICK_DIALOG      126
#define IDR_MAINFRAME                   128
#define IDR_ALCAN_TYPE                  129
#define IDD_DIALOG_VIEW                 130
#define IDR_VIEW_MENU                   131
#define IDD_DIALOG1                     132
#define IDD_DIALOG_DETAILS              133
#define IDD_DIALOG_DEFECTS              134
#define IDR_RB_POPUP_MENU               135
#define IDD_DIALOG_BLANK_SHEET          136
#define IDD_DIALOG_GLOBAL_UT            137
#define IDD_DIALOG_PROBE                138
#define IDD_PAINTBRUSH_PROBE_DLG        138
#define IDD_DIALOG_DAC_BLOCKS           139
#define IDD_DIALOG_DACBLOCK_TABLE       140
#define IDD_DIALOG_COMPONENT            141
#define IDD_DIALOG_BAR_GRAPHS           143
#define IDD_DIALOG_PALETTE              144
#define IDD_PALETTE_FBH_PAGE            144
#define IDR_RB_PALETTE_MENU             145
#define IDR_TOOLBAR                     146
#define IDI_PLATE_KNIFE_FORK            148
#define IDD_PR30_TIMESLOT_DIALOG        149
#define IDD_DIALOG_MOVETO               150
#define IDD_HEXDUMP_DIALOG              151
#define IDR_RB_DAC_TABLE_MENU           152
#define IDD_DIALOG_ULTRASONICS_GENERAL  153
#define IDD_DIALOG_FLUKE                154
#define IDD_DIALOGBAR                   155
#define IDR_RB_MOVETO_MENU              155
#define IDD_DIALOG_PROMPT               156
#define IDD_DIALOG_SENTENCE             157
#define IDD_DIALOG_BEAM_PROFILE         158
#define IDR_BEAM_PROFILE_MENU           159
#define IDD_MICRO_SCAN_DIALOG           160
#define IDR_RB_DEFECTS_MENU             161
#define IDR_RB_OSCILLOSCOPE_MENU        162
#define IDD_OPERATOR_UT_DIALOG          163
#define IDD_TANK_DIALOG                 164
#define IDD_ANNOTATE_DIALOG             166
#define IDR_PMAC_MENU                   167
#define IDD_TUNING_DIALOG               168
#define IDR_RB_DAC_MENU                 169
#define IDR_RB_SCOPE_MENU               170
#define IDD_AXES_SHEET                  171
#define IDD_DIRECTORIES_DIALOG          172
#define IDD_DSP_TIMS_DIALOG             173
#define IDD_PROBE_PAGE                  174
#define IDD_PALETTE_AMPLITUDE_DIALOG    175
#define IDD_PALETTE_THICK_DIALOG1       176
#define IDD_PALETTE_DIALOG              177
#define IDD_FILES_DIALOG                178
#define IDD_REPORT_PRINT_DIALOG         179
#define IDC_CURSOR_H_MOVE               179
#define IDD_LINE_PROPERTIES_DIALOG      180
#define IDC_CURSOR_V_MOVE               180
#define IDD_IMAGE_PROPERTIES_DIALOG     181
#define IDC_CURSOR_CROSS                181
#define IDD_DATE_PROPERTIES_DIALOG      182
#define IDC_CURSOR_ALL_MOVE             182
#define IDD_BARGRAPH_PROPERTIES_DIALOG2 183
#define IDD_LIST_PROPERTIES_DIALOG      184
#define IDR_MENU1                       184
#define IDD_RECTANGLE_PROPERTIES_DIALOG 185
#define IDR_RB_REPORT_MENU              185
#define IDD_TEXT_PROPERTIES_DIALOG      186
#define IDD_POSITION_DIALOG             187
#define IDD_SPECTRUM_ANALYZER_DIALOG    188
#define IDD_PROGRESS_DIALOG             189
#define IDD_CARDS_DIALOG1               190
#define IDD_ACQIRIS_DIALOG              192
#define IDD_PERMISSION_DIALOG           193
#define IDR_TOOLBAR_PRINT               196
#define IDD_PMAC_DIALOG                 197
#define IDR_RB_MAINFRAME_MENU           198
#define IDD_SQUINT_DIALOG               199
#define IDR_TOOLBAR_VIEW                200
#define IDR_RB_BEAMPROFILE_MENU         202
#define IDD_PMAC_VARIABLES_DIALOG       205
#define IDD_PMAC_DOWNLOAD_DIALOG        206
#define IDD_GATES_PAGE1                 207
#define IDD_PR30_TIMESLOT_DIALOG1       209
#define IDD_DEVICE_RESOURCES_DIALOG1    212
#define IDR_RB_GATES_MENU               213
#define IDD_PMAC_SHEET                  214
#define IDD_VSMPO_POS_DIALO             215
#define IDD_DATE_PROPERTIES_DIALOG1     216
#define IDD_BARGRAPH_PROPERTIES_DIALOG21 217
#define IDD_GATES_PAGE2                 218
#define IDD_IMAGE_PROPERTIES_DIALOG1    219
#define IDD_LINE_PROPERTIES_DIALOG1     220
#define IDD_SCAN_SHEET                  221
#define IDD_VSMPO_DETAILS               222
#define IDD_PEEK_PAGE                   223
#define IDR_VSMPO_TOOLBAR               224
#define IDD_LIST_PROPERTIES_DIALOG1     225
#define IDR_MENU2                       226
#define IDD_VSMPO_SCAN_DIALOG           227
#define IDD_RECTANGLE_PROPERTIES_DIALOG1 228
#define IDD_REPORT_PRINT_DIALOG1        229
#define IDD_TEXT_PROPERTIES_DIALOG1     230
#define IDD_PMAC_MOVE_PAGE              231
#define IDR_REPORT_PRINT_MENU           232
#define IDD_SPLASHSCREEN                233
#define IDR_ANNOTATION_MENU             234
#define IDR_RB_ANNOTATION_MENU          235
#define IDR_RB_MICRO_MENU               236
#define IDD_TEST_BLOCK_PAGE             237
#define IDD_FEATURE_EDIT_DIALOG         238
#define IDD_DATA_VALUE_PROPERTIES_DLG   239
#define IDR_RB_FEATURE_MENU             240
#define IDR_RB_REPORT_SELECT_MENU       241
#define IDD_PMAC_ENCODERS_PAGE          242
#define IDR_MAINFRAME_ALRO              243
#define IDD_PMAC_TUNING_PAGE            244
#define IDD_FBH_EQUIVELANTS             245
#define IDR_RB_FBH_LIST_MENU            246
#define IDD_AXES_STATUS_ALPROM_DIALOG   247
#define IDD_ALPRO_DETAILS               248
#define IDR_ALPRO_MOTION_TOOLBAR        250
#define IDR_TOOLBAR_ULTRASONICS         251
#define IDD_SOUTHWEST_POS_DIALOG        253
#define IDR_MAINFRAME_SOUTHWEST         254
#define IDC_STATIC_VIEW                 1000
#define IDC_COMBO_CUSTOMER              1001
#define IDC_EDIT_DISTANCE               1002
#define IDC_EDIT                        1003
#define IDC_EDIT_FAST_SCAN_SIZE         1003
#define IDC_SPIN                        1004
#define IDC_SPIN_FAST_SCAN_SIZE         1004
#define IDC_DELAY_SLIDER                1004
#define IDC_EDIT_BODY_THRESHOLD         1005
#define IDC_EDIT_SLOW_SCAN_SIZE         1005
#define IDC_WIDTH_SLIDER                1005
#define IDC_EDIT_BACKWALL_THRESHOLD     1006
#define IDC_SPIN_SLOW_SCAN_SIZE         1006
#define IDC_SPIN_BODY_THRESHOLD         1007
#define IDC_EDIT_FAST_INCREMENT         1007
#define IDC_SPIN_BACKWALL_THRESHOLD     1008
#define IDC_OFFSET_SLIDER               1008
#define IDC_EDIT_NUMBER                 1009
#define IDC_SPIN_FAST_INCREMENT         1009
#define IDC_GAIN_SLIDER                 1009
#define IDC_EDIT_CAST                   1010
#define IDC_DAC_GAIN_SLIDER             1010
#define IDC_EDIT_BATCH                  1010
#define IDC_EDIT_ALLOY                  1011
#define IDC_EDIT_SLOW_INCREMENT         1011
#define IDC_DAC_OFFSET_SLIDER           1011
#define IDC_EDIT_SPECIFICATION          1012
#define IDC_COMBO_PREAMP_GAIN           1012
#define IDC_EDIT_ACCEPTANCE             1013
#define IDC_SPIN_SLOW_INCREMENT         1013
#define IDC_LIST1                       1014
#define IDC_EDIT_MAIN_GAIN              1014
#define IDC_LIST_DEFECTS                1014
#define IDC_EDIT_STANDARD               1014
#define IDC_LIST_FILES                  1014
#define IDC_LIST_PROBES                 1014
#define IDC_LIST_TEST_BLOCK             1014
#define IDC_LIST_FEATURE                1014
#define IDC_LIST_FBH                    1014
#define IDC_EDIT_NUMBER_TIMESLOTS       1015
#define IDC_EDIT_LASTSETTINGS_PATH      1015
#define IDC_EDIT_WATER_VELOCITY         1015
#define IDC_SPIN_MAIN_GAIN              1016
#define IDC_SPIN_NUMBER_TIMESLOTS       1016
#define IDC_EDIT_PROFILES_PATH          1016
#define IDC_EDIT_CHANNEL_NUMBER         1017
#define IDC_SPIN_WATER_VELOCITY         1017
#define IDC_EDIT_PULSE_WIDTH            1018
#define IDC_COMBO_PMAC_PRESENT          1018
#define IDC_EDIT_IMAGES_PATH            1018
#define IDC_SPIN_CHANNEL_NUMBER         1019
#define IDC_EDIT_APTSOURCE_PATH         1019
#define IDC_SPIN_PULSE_WIDTH            1020
#define IDC_EDIT_DESCRIPTION            1020
#define IDC_EDIT_ULTRASONICS_PATH       1020
#define IDC_EDIT_MANUFACTURER           1021
#define IDC_EDIT_PALETTE_PATH           1021
#define IDC_SPIN_MATERIAL_VELOCITY      1021
#define IDC_EDIT_PULSE_VOLTAGE          1022
#define IDC_EDIT_SERIAL_NUMBER          1022
#define IDC_EDIT_SCAN_PATH              1022
#define IDC_EDIT_FREQUENCY              1023
#define IDC_SPIN_PULSE_VOLTAGE          1024
#define IDC_EDIT_HEIGHT                 1024
#define IDC_EDIT_MARKER_X               1025
#define IDC_EDIT_PRF                    1026
#define IDC_EDIT_MARKER_Y               1026
#define IDC_COMBO_SI6_PRESENT           1026
#define IDC_LIST_ELEMENTS               1027
#define IDC_COMBO_GATE_NUMBER           1027
#define IDC_SPIN_PRF                    1028
#define IDC_BUTTON_GOTO                 1028
#define IDC_TRIGGER_MODE_COMBO          1029
#define IDC_BUTTON_CENTER               1029
#define IDC_COMBO_GATE_MODE             1029
#define IDC_COMBO_FILTER_RANGE          1030
#define IDC_BLANKING_EDIT               1030
#define IDC_EDIT_BLOCKNUMBER            1030
#define IDC_BLANKING_SPIN               1031
#define IDC_SPIN_BLOCK_NUMBER           1031
#define IDC_EDIT_GATE_DELAY             1031
#define IDC_EDIT_FILTER_OFFSET          1032
#define IDC_DELAY_EDIT                  1032
#define IDC_BUTTON_UPDATE_AMP           1032
#define IDC_DELAY_SPIN                  1033
#define IDC_EDIT_AMP                    1033
#define IDC_EDIT_MEASURED               1033
#define IDC_EDIT_GATE_WIDTH             1033
#define IDC_EDIT_Y_LEFT                 1033
#define IDC_SPIN_FILTER_OFFSET          1034
#define IDC_START_THRESHOLD_EDIT        1034
#define IDC_LIST                        1034
#define IDC_EDIT_Z_LEFT                 1034
#define IDC_STOP_THRESHOLD_EDIT         1035
#define IDC_SPIN_THICKNESS              1035
#define IDC_STATIC_DELAY                1035
#define IDC_SERIAL_NUMBER_EDIT          1035
#define IDC_COMBO_LOW_PASS              1036
#define IDC_START_THRESHOLD_SPIN        1036
#define IDC_EDIT_NEARDEADZONE           1036
#define IDC_STATIC_WIDTH                1036
#define IDC_TYPE_EDIT                   1036
#define IDC_EDIT_ZT_LEFT                1036
#define IDC_STOP_THRESHOLD_SPIN         1037
#define IDC_SPIN_NEARDEADZONE           1037
#define IDC_MEMORY_SIZE_EDIT            1037
#define IDC_EDIT_YT_LEFT                1037
#define IDC_START_SLOPE_COMBO           1038
#define IDC_EDIT_FARDEADZONE            1038
#define IDC_MOD_RECORD_EDIT             1038
#define IDC_STOP_SLOPE_COMBO            1039
#define IDC_SPIN_FARDEADZONE            1039
#define IDC_TESTER_EDIT                 1039
#define IDC_EDIT_THICKNESS              1040
#define IDC_VSCALE_EDIT                 1040
#define IDC_TEST_DATE_EDIT              1040
#define IDC_EDIT_VELOCITY               1041
#define IDC_VSCALE_SPIN                 1041
#define IDC_DSP_PRESENT                 1041
#define IDC_STATIC_TEXT_COLOR           1041
#define IDC_SPIN_VELOCITY               1042
#define IDC_VUNITS_COMBO                1042
#define IDC_BUTTON_GATESFROMGAUGE       1043
#define IDC_BLANK_UNITS_COMBO           1043
#define IDC_EDIT_I3                     1043
#define IDC_BUTTON_GATESFROMTHICKNESS   1044
#define IDC_DELAY_UNITS_COMBO           1044
#define IDC_COMBO_PROGRAM               1044
#define IDC_BUTTON_GATESHALFTHICKNESS   1045
#define IDC_WATER_VELOCITY_EDIT         1045
#define IDC_BUTTON_DOWNLOAD             1045
#define IDC_BUTTON_GATESHALFGAUGE       1045
#define IDC_STATIC_BAR_GRAPH            1045
#define IDC_BUTTON_GATES20MM            1046
#define IDC_WATER_VELOCITY_SPIN         1046
#define IDC_AXIS_STEPSIZE               1046
#define IDC_EDIT_INTERRUPT_COUNT        1046
#define IDC_EDIT_WATERPATH              1047
#define IDC_BUTTON_ADD                  1047
#define IDC_MATERIAL_VELOCITY_EDIT      1047
#define IDC_EDIT_I8                     1047
#define IDC_STATIC_ENTRIES              1047
#define IDC_SPIN_WATERPATH              1048
#define IDC_MATERIAL_VELOCITY_SPIN      1048
#define IDC_BUTTON3                     1049
#define IDC_BUTTON_DELETE               1049
#define IDC_BUTTON_MOVETO_WATERPATH     1049
#define IDC_EDIT_DSP_RESULT             1049
#define IDC_COMBO_MODE                  1049
#define IDC_BUTTON_CLEARALL             1050
#define IDC_COMBO_MODE2                 1050
#define IDC_EDIT_JOY_DEV_X              1051
#define IDC_X_AXIS_EDIT                 1051
#define IDC_EDIT_STEPSIZE               1051
#define IDC_EDIT_JOY_DEV_Y              1052
#define IDC_Y_AXIS_EDIT                 1052
#define IDC_COMBO_SPECIFICATION         1053
#define IDC_COMBO_ACCESS_LEVEL          1053
#define IDC_BUTTON_PLATE_SIZE           1053
#define IDC_EDIT_JOY_DEV_Z              1053
#define IDC_Z_AXIS_EDIT                 1053
#define IDC_COMBO_ACCEPTANCE            1054
#define IDC_LIST_NAMES                  1054
#define IDC_BUTTON_MOVETO_CENTER        1054
#define IDC_EDIT_JOY_DEV_S              1054
#define IDC_S_AXIS_EDIT                 1054
#define IDC_BUTTON_AUTO_WATER_PATH      1054
#define IDC_BUTTON_SCAN                 1055
#define IDC_EDIT_CURRENT_PROGRAM        1055
#define IDC_T_AXIS_EDIT                 1055
#define IDC_EDIT_MIN                    1055
#define IDC_JOY_PTR_EDIT                1056
#define IDC_COMBO_FORCE_CALIBRATION     1057
#define IDC_LIST_LEVELS                 1057
#define IDC_JOY_ARRAY_EDIT              1057
#define IDC_EDIT_LEVEL                  1058
#define IDC_COMBO_FORCE_LOGON           1058
#define IDC_SWITCHES_EDIT               1058
#define IDC_EDIT_FBH                    1059
#define IDC_SPIN_STEPSIZE               1059
#define IDC_STATIC_COLOR                1060
#define IDC_STATIC_BW_PASSED            1061
#define IDC_EDIT_DEFECT_THRESHOLD       1061
#define IDC_SPIN_MIN                    1061
#define IDC_STATIC_BW_FAILED            1062
#define IDC_SPIN_DEFECT_THRESHOLD       1062
#define IDC_EDIT_HIGH_GAIN              1063
#define IDC_SPIN_HIGH_GAIN              1064
#define IDC_EDIT_MIN_TOLERANCE          1065
#define IDC_EDIT_MAX_TOLERANCE          1066
#define IDC_EDIT_NUMBER_DAC_BLOCKS      1066
#define IDC_SPIN_NUMBER_DAC_BLOCKS      1067
#define IDC_AXIS_UNITS_COMBO            1068
#define IDC_LIST_PROGRAMS               1068
#define IDC_ACCEPT_BUTTON               1070
#define IDC_AXIS_AVAILABLE_CHECK        1071
#define IDC_CHECK_JOYSTICK_REVERSE      1072
#define IDC_EDIT_ELAPSED_TIME           1072
#define IDC_EDIT_POS_COUNTER            1073
#define IDC_COMBO_DISPLAY_MODE          1074
#define IDC_BUTTON_PRINT                1075
#define IDC_EDIT_TANK_WIDTH             1076
#define IDC_CHECK_IN_POSITION           1076
#define IDC_CHECK_BW_REVERSE            1076
#define IDC_CHECK_MOTOR_REVERSE         1077
#define IDC_EDIT_TANK_HEIGHT            1077
#define IDC_EDIT_SAFETY_ZONE_MIN        1078
#define IDC_CHECK_HOMED                 1078
#define IDC_EDIT_MIN_TRAVEL             1079
#define IDC_EDIT_SAFETY_ZONE_MAX        1079
#define IDC_EDIT_MAX_TRAVEL             1080
#define IDC_EDIT_DRIVER_NAME            1080
#define IDC_EDIT_STATUS                 1081
#define IDC_CHECK_SOFT_ERROR            1081
#define IDC_EDIT_HOME_OFFSET            1082
#define IDC_BUTTON_LOOKUP               1082
#define IDC_EDIT_POS                    1083
#define IDC_BUTTON_STOP                 1083
#define IDC_BUTTON_START                1084
#define IDC_CHECK_HARD_ERROR            1084
#define IDC_EDIT_COUNT                  1085
#define IDC_COMBO_HARDWARE              1085
#define IDC_EDIT_LASTSETTINGS           1086
#define IDC_CHECK_MIN_SWITCH            1086
#define IDC_EDIT_ENCODER_POS            1087
#define IDC_BUTTON_BROWSE               1087
#define IDC_BUTTON_CANCEL               1088
#define IDC_CHECK_MAX_SWITCH            1088
#define IDC_BUTTON_INSTALL              1089
#define IDC_EDIT_POSITION_1             1089
#define IDC_LIST_MEMORY                 1090
#define IDC_EDIT_DESIRE_POS_1           1090
#define IDC_COMBO_DEVICE                1091
#define IDC_EDIT_POSITION_2             1091
#define IDC_EDIT_IN_POS_ERR             1092
#define IDC_CHECK_HOMED_1               1092
#define IDC_CHECK_IN_POS_1              1093
#define IDC_BUTTON_STORE_POS            1093
#define IDC_CHECK_MIN_SWITCH_1          1094
#define IDC_COMBO_PAGE_NUMBER           1094
#define IDC_CHECK_MAX_SWITCH_1          1095
#define IDC_CHECK_SOFT_ERROR_1          1096
#define IDC_SPIN_BW_DELAY               1096
#define IDC_CHECK_HARD_ERROR_1          1097
#define IDC_SPIN_BODY_DELAY             1097
#define IDC_EDIT_STORE_PATH             1098
#define IDC_EDIT_STATUS_1               1098
#define IDC_SPIN_BW_WIDTH               1098
#define IDC_EDIT_ARCHIVE_PATH           1099
#define IDC_DEFAULT_BUTTON              1099
#define IDC_EDIT_DESIRE_POS_2           1099
#define IDC_EDIT_BW_DELAY               1099
#define IDC_TRIGGER_SOURCE_COMBO        1099
#define IDC_BUTTON_BROWSE_STORE         1100
#define IDC_EDIT_STATUS_2               1100
#define IDC_EDIT_BW_WIDTH               1100
#define IDC_COMBO                       1101
#define IDC_BUTTON_BROWSE_ARCHIVE       1101
#define IDC_CHECK_HOMED_2               1101
#define IDC_EDIT_BODY_WIDTH             1101
#define IDC_CHECK_IN_POS_2              1102
#define IDC_SPIN_BODY_WIDTH2            1102
#define IDC_SPIN_BODY_WIDTH             1102
#define IDC_EDIT_UT_PATH                1102
#define IDC_CHECK_MIN_SWITCH_2          1103
#define IDC_EDIT_THICKNESS_DELAY        1103
#define IDC_BUTTON_BROWSE_UT            1103
#define IDC_CHECK_MAX_SWITCH_2          1104
#define IDC_EDIT_BODY_DELAY             1104
#define IDC_CHECK_SOFT_ERROR_2          1105
#define IDC_SPIN_THICKNESS_DELAY        1105
#define IDC_CHECK_HARD_ERROR_2          1106
#define IDC_EDIT_TIMS_WIDTH             1106
#define IDC_EDIT_POSITION_3             1107
#define IDC_EDIT_DESIRE_POS_3           1108
#define IDC_COMBO_BODY_MODE             1108
#define IDC_EDIT_STATUS_3               1109
#define IDC_CHECK_HOMED_3               1110
#define IDC_CHECK_IN_POS_3              1111
#define IDC_EDIT_BODY_FIR               1111
#define IDC_CHECK_MIN_SWITCH_3          1112
#define IDC_SPIN_BODY_FIR               1112
#define IDC_STATIC_TEXT                 1112
#define IDC_CHECK_MAX_SWITCH_3          1113
#define IDC_EDIT_BODY_MAX_D_WIDTH       1113
#define IDC_EDIT_BODY_MAX_WIDTH         1113
#define IDC_PROGRESS_BAR                1113
#define IDC_CHECK_SOFT_ERROR_3          1114
#define IDC_SPIN_BODY_MAX_D_WIDTH       1114
#define IDC_SPIN_BODY_MAX_WIDTH         1114
#define IDC_CHECK_HARD_ERROR_3          1115
#define IDC_COMBO_BW_MODE               1115
#define IDC_EDIT_POSITION_4             1116
#define IDC_EDIT_BODY_BLANKING          1116
#define IDC_EDIT_DESIRE_POS_4           1117
#define IDC_SPIN_BODY_BLANKING          1117
#define IDC_EDIT_STATUS_4               1118
#define IDC_EDITBW_DEFECT_THRESHOLD     1118
#define IDC_EDIT_ADC_ADDRESS            1118
#define IDC_CHECK_HOMED_4               1119
#define IDC_EDIT_DSP_ADDRESS            1119
#define IDC_EDIT_BODY_DEFECT_THRESHOLD  1119
#define IDC_COMBO_DAMPING               1120
#define IDC_CHECK_IN_POS_4              1120
#define IDC_EDIT_NOTES                  1120
#define IDC_CHECK_MIN_SWITCH_4          1121
#define IDC_SPIN_DELAY                  1122
#define IDC_CHECK_STORE                 1122
#define IDC_CHECK_MAX_SWITCH_4          1122
#define IDC_CHECK_PERIODIC_UPDATE       1122
#define IDC_SPIN_WIDTH                  1123
#define IDC_CHECK_ARCHIVE               1123
#define IDC_CHECK_SOFT_ERROR_4          1123
#define IDC_SPIN_BW_DEFECT_LEVEL        1123
#define IDC_EDIT_CONSTANT               1124
#define IDC_CHECK_HARD_ERROR_4          1124
#define IDC_COMBO_RECTIFIER             1124
#define IDC_EDIT_GATE_THRESHOLD         1124
#define IDC_BUTTON_SAVE                 1125
#define IDC_EDIT_POSITION_5             1125
#define IDC_EDIT_IRQ_COUNT              1125
#define IDC_SPIN_GATE_THRESHOLD         1125
#define IDC_SPIN_BODY_DEFECT_LEVEL      1125
#define IDC_EDIT_DPRAM                  1126
#define IDC_EDIT_DESIRE_POS_5           1126
#define IDC_EDIT_GPD_MAX_THRESHOLD      1126
#define IDC_STATIC_THRESHOLD            1126
#define IDC_EDIT_JUMP_TO                1127
#define IDC_EDIT_STATUS_5               1127
#define IDC_EDIT_GPD_MIN_THRESHOLD      1127
#define IDC_STATIC_VALUE                1128
#define IDC_BUTTON_JUMP_TO              1128
#define IDC_CHECK_HOMED_5               1128
#define IDC_EDIT_GPD0_AMPLITUDE         1128
#define IDC_COMBO_DETECTION             1128
#define IDC_LIST_I_VARIABLES            1129
#define IDC_CHECK_IN_POS_5              1129
#define IDC_EDIT_BW_GAIN                1129
#define IDC_COMBOSTART_SLOPE            1129
#define IDC_CHECK_MIN_SWITCH_5          1130
#define IDC_SPIN_BW_GAIN                1130
#define IDC_COMBO_STOP_SLOPE            1130
#define IDC_EDIT_PMAC_STR               1131
#define IDC_CHECK_MAX_SWITCH_5          1131
#define IDC_LIST_TVG                    1131
#define IDC_COMBO_DETECTION2            1131
#define IDC_EDIT_START_POS              1132
#define IDC_BUTTON_NEXT                 1132
#define IDC_CHECK_SOFT_ERROR_5          1132
#define IDC_EDIT_TARGET                 1132
#define IDC_COMBOSTART_SLOPE2           1132
#define IDC_EDIT_FINISH_POS             1133
#define IDC_BUTTON_PREVIOUS             1133
#define IDC_CHECK_HARD_ERROR_5          1133
#define IDC_COMBO_STOP_SLOPE2           1133
#define IDC_BUTTON_STORE_START_POS      1134
#define IDC_LIST_DESCRIPTION            1134
#define IDC_EDIT_VELOCITY_1             1134
#define IDC_BUTTON_MINUS100             1134
#define IDC_BUTTON_STORE_FINISH_POS     1135
#define IDC_EDIT_VELOCITY_2             1135
#define IDC_BUTTON_PLUS100              1135
#define IDC_BUTTON_MOVETO_START         1136
#define IDC_BUTTON_DO_IT                1136
#define IDC_EDIT_VELOCITY_3             1136
#define IDC_BUTTON_MOVETO_FINISH        1137
#define IDC_COMBO_COPY_TO               1137
#define IDC_EDIT_VELOCITY_4             1137
#define IDC_BUTTON_FIND_HOLE            1137
#define IDC_COMBO_COPY_WHAT             1138
#define IDC_EDIT_VELOCITY_5             1138
#define IDC_BUTTON_COPY                 1139
#define IDC_CHECK_HOME_SWITCH_1         1139
#define IDC_EDIT_DELTA_X                1140
#define IDC_CHECK_HOME_SWITCH_2         1140
#define IDC_EDIT_DELTA_Y                1141
#define IDC_CHECK_HOME_SWITCH_3         1141
#define IDC_EDIT_DELTA_Z                1142
#define IDC_CHECK_HOME_SWITCH_4         1142
#define IDC_EDIT_WATER_PATH             1143
#define IDC_CHECK_HOME_SWITCH_5         1143
#define IDC_EDIT_WATER_PATH_ERROR       1144
#define IDC_COMBO_SCALE_TYPE            1144
#define IDC_EDIT_WATER_PATHERROR        1144
#define IDC_EDIT_WIDTH                  1145
#define IDC_BUTTON_REMOVE               1145
#define IDC_COMBO_FLUKE                 1146
#define IDC_COMBO_CHANNEL               1147
#define IDC_EDIT_SENSITIVITY            1148
#define IDC_SPIN_SENSITIVITY            1149
#define IDC_EDIT_MIN_SENSITIVITY        1150
#define IDC_EDIT_CURRENT_SPEED          1151
#define IDC_EDIT_CURRENT_STATUS         1151
#define IDC_EDIT_MAX_SENSITIVITY        1151
#define IDC_EDIT_ERROR_COUNT            1152
#define IDC_BUTTON_DISABLE_LIMIT_SWITCHES 1152
#define IDC_BUTTON_RESTART_DSP          1153
#define IDC_BUTTON_ENABLE_LIMIT_SWITCHES 1153
#define IDC_COMBO_JOYSTICK_SPEED        1154
#define IDC_STATIC_MESSAGE              1155
#define IDC_EDIT_RANGE                  1155
#define IDC_COMBO_SENTENCE              1156
#define IDC_COMBO_COMM_PORT             1156
#define IDC_SPIN_RANGE                  1156
#define IDC_EDIT_LOT_NUMBER             1157
#define IDC_EDIT_OPERATOR               1157
#define IDC_EDIT_TOP_LEVEL              1157
#define IDC_COMBO_FACE                  1158
#define IDC_SPIN_TOP_LEVEL              1158
#define IDC_COMBO_SHIFT                 1159
#define IDC_COMBO_SEPARATOR             1159
#define IDC_EDIT_YSCAN_LENGTH           1160
#define IDC_COMBO_EOL                   1160
#define IDC_EDIT_XSCAN_LENGTH           1161
#define IDC_EDIT_X_INCREMENT            1162
#define IDC_STATIC_COLOR_0              1165
#define IDC_STATIC_COLOR_1              1166
#define IDC_EDIT_SI6_IO_ADDRS           1167
#define IDC_STATIC_COLOR_2              1167
#define IDC_EDIT_SI6_IO_RANGE           1168
#define IDC_STATIC_COLOR_3              1168
#define IDC_EDIT_SI6_MEM_ADDRS          1169
#define IDC_STATIC_COLOR_4              1169
#define IDC_EDIT_SI6_MEM_RANGE          1170
#define IDC_STATIC_COLOR_5              1170
#define IDC_EDIT_SI6_IRQ                1171
#define IDC_STATIC_COLOR_6              1171
#define IDC_EDIT_UT_IO_ADDRS            1172
#define IDC_STATIC_COLOR_7              1172
#define IDC_EDIT_UT_IO_RANGE            1173
#define IDC_EDIT_UT_MEM_ADDRS           1174
#define IDC_EDIT_UT_MEM_RANGE           1175
#define IDC_EDIT_UT_IRQ                 1176
#define IDC_STATIC_GAIN0                1176
#define IDC_EDIT_PMAC_IO_ADDRS          1177
#define IDC_STATIC_GAIN1                1177
#define IDC_EDIT_PMAC_IO_RANGE          1178
#define IDC_STATIC_GAIN2                1178
#define IDC_EDIT_PMAC_MEM_ADDRS         1179
#define IDC_EDIT_POSITION_6             1179
#define IDC_STATIC_GAIN3                1179
#define IDC_EDIT_PMAC_MEM_RANGE         1180
#define IDC_EDIT_DESIRE_POS_6           1180
#define IDC_STATIC_GAIN4                1180
#define IDC_EDIT_PMAC_IRQ               1181
#define IDC_EDIT_STATUS_6               1181
#define IDC_STATIC_GAIN5                1181
#define IDC_EDIT_SI6_VERSION            1182
#define IDC_CHECK_HOMED_6               1182
#define IDC_STATIC_GAIN6                1182
#define IDC_EDIT_ULTRASONICS_VERSION    1183
#define IDC_CHECK_IN_POS_6              1183
#define IDC_STATIC_GAIN7                1183
#define IDC_EDIT_PMAC_VERSION           1184
#define IDC_CHECK_MIN_SWITCH_6          1184
#define IDC_EDIT4                       1184
#define IDC_CHECK_MAX_SWITCH_6          1185
#define IDC_EDIT5                       1185
#define IDC_CHECK_SOFT_ERROR_6          1186
#define IDC_COMBO_DSP_CARD_TYPE         1186
#define IDC_EDIT_SPEED                  1186
#define IDC_CHECK_HARD_ERROR_6          1187
#define IDC_EDIT_TVG_COEFFICIENT        1187
#define IDC_EDIT_MEM_OFFSET             1188
#define IDC_EDIT_POSITION_7             1188
#define IDC_EDIT_BUZZER_TIME            1188
#define IDC_EDIT_MAX_SPEED              1189
#define IDC_EDIT_DESIRE_POS_7           1189
#define IDC_CHECK_EMERGENCY_SWITCH_BANNER 1189
#define IDC_EDIT_HOME_SPEED             1190
#define IDC_EDIT_STATUS_7               1190
#define IDC_EDIT_ACCELERATION           1191
#define IDC_CHECK_HOMED_7               1191
#define IDC_CHECK_IN_POS_7              1192
#define IDC_EDIT_JOYSTICK_GAIN          1193
#define IDC_CHECK_MIN_SWITCH_7          1193
#define IDC_EDIT_JOYSTICK_NUMBER        1194
#define IDC_CHECK_MAX_SWITCH_7          1194
#define IDC_CHECK_SOFT_ERROR_7          1195
#define IDC_CHECK_HARD_ERROR_7          1196
#define IDC_CHECK_FLYING_GATE           1196
#define IDC_SLIDER_ZOOM_LEVEL           1196
#define IDC_SLIDER_0_DB_POINT           1197
#define IDC_EDIT_VELOCITY_6             1197
#define IDC_COMBO_TANK                  1198
#define IDC_EDIT_VELOCITY_7             1198
#define IDC_CHECK_HOME_SWITCH_6         1199
#define IDC_CHECK_RED_BLUE              1200
#define IDC_CHECK_HOME_SWITCH_7         1200
#define IDC_COMBO_COPIES                1201
#define IDC_EDIT_POSITION_11            1201
#define IDC_EDIT_POSITION_8             1201
#define IDC_EDIT_DESIRE_POS_11          1202
#define IDC_EDIT_DESIRE_POS_8           1202
#define IDC_CHECK_MAX_SWITCH_8          1203
#define IDC_EDIT_NB                     1203
#define IDC_EDIT_STATUS_11              1203
#define IDC_CHECK_HOMED_11              1204
#define IDC_CHECK_HOMED_8               1204
#define IDC_EDIT_MIN_PRF                1205
#define IDC_CHECK_IN_POS_11             1205
#define IDC_CHECK_IN_POS_8              1205
#define IDC_EDIT_MAX_PRF                1206
#define IDC_CHECK_MIN_SWITCH_11         1206
#define IDC_CHECK_MIN_SWITCH_8          1206
#define IDC_EDIT_X_SAMPLES              1207
#define IDC_CHECK_MAX_SWITCH_11         1207
#define IDC_EDIT_Y_SAMPLES              1208
#define IDC_CHECK_SOFT_ERROR_11         1208
#define IDC_CHECK_SOFT_ERROR_8          1208
#define IDC_SPIN_X_SAMPLES              1209
#define IDC_EDIT_VELOCITY_8             1209
#define IDC_SPIN_Y_SAMPLES              1210
#define IDC_CHECK_HOME_SWITCH_8         1210
#define IDC_BUTTON_CALCULATE            1211
#define IDC_CHECK_HARD_ERROR_11         1211
#define IDC_CHECK_HARD_ERROR_8          1211
#define IDC_CHECK_MAX_SWITCH_9          1212
#define IDC_EDIT_PERCENTAGE_SPEED       1212
#define IDC_EDIT_POSITION_12            1212
#define IDC_SPIN_SCAN_SPEED             1213
#define IDC_EDIT_DESIRE_POS_12          1213
#define IDC_EDIT_DESIRE_POS_9           1213
#define IDC_EDIT_STATUS_12              1214
#define IDC_EDIT_STATUS_9               1214
#define IDC_EDIT_LOGON_TIMEOUT          1215
#define IDC_CHECK_HOMED_12              1215
#define IDC_CHECK_HOMED_9               1215
#define IDC_SPIN_LOGON_TIMEOUT          1216
#define IDC_CHECK_IN_POS_12             1216
#define IDC_CHECK_IN_POS_9              1216
#define IDC_EDIT_PATH                   1217
#define IDC_BUTTON_PROFILE              1217
#define IDC_CHECK_MIN_SWITCH_12         1217
#define IDC_CHECK_MIN_SWITCH_9          1217
#define IDC_BUTTON_IMAGES               1218
#define IDC_CHECK_MAX_SWITCH_12         1218
#define IDC_CHECK_HOME_SWITCH_13        1218
#define IDC_COMBO_DAC_OFF_ON            1219
#define IDC_BUTTON_APTSOURCE            1219
#define IDC_CHECK_SOFT_ERROR_12         1219
#define IDC_CHECK_SOFT_ERROR_9          1219
#define IDC_BUTTON_ULTRASONICS          1220
#define IDC_CHECK_HARD_ERROR_12         1220
#define IDC_CHECK_HARD_ERROR_9          1220
#define IDC_EDIT_PHYSICAL_AXIS          1221
#define IDC_CHECK_MAX_SWITCH_10         1221
#define IDC_BUTTON_PALETTES             1221
#define IDC_EDIT_VELOCITY_9             1222
#define IDC_CHECK_HOME_SWITCH_9         1222
#define IDC_EDIT_POSITION_13            1223
#define IDC_EDIT_POSITION_10            1223
#define IDC_EDIT_DESIRE_POS_13          1224
#define IDC_EDIT_DESIRE_POS_10          1224
#define IDC_EDIT_STATUS_13              1225
#define IDC_EDIT_STATUS_10              1225
#define IDC_EDIT_XT_MINMAX              1226
#define IDC_CHECK_HOMED_13              1226
#define IDC_CHECK_HOMED_10              1226
#define IDC_EDIT_YT_MINMAX              1227
#define IDC_CHECK_IN_POS_13             1227
#define IDC_CHECK_IN_POS_10             1227
#define IDC_BUTTON_ACCEPT               1228
#define IDC_CHECK_MIN_SWITCH_13         1228
#define IDC_CHECK_MIN_SWITCH_10         1228
#define IDC_EDITELEMENT                 1229
#define IDC_CHECK_MAX_SWITCH_13         1229
#define IDC_COMBO_JOB_NUMBER            1230
#define IDC_CHECK_SOFT_ERROR_13         1230
#define IDC_CHECK_SOFT_ERROR_10         1230
#define IDC_EDIT_X_LENGTH               1231
#define IDC_CHECK_HARD_ERROR_13         1231
#define IDC_CHECK_HARD_ERROR_10         1231
#define IDC_EDIT_Y_WIDTH                1232
#define IDC_EDIT_VELOCITY_10            1232
#define IDC_COMBO_SAFETY                1233
#define IDC_CHECK_HOME_SWITCH_10        1233
#define IDC_COMBO_CENTRE_DIVIDE         1234
#define IDC_EDIT_X_LEFT                 1235
#define IDC_EDIT_X_RIGHT                1236
#define IDC_BUTTON_HOME_OFFSET          1240
#define IDC_EDITMATERIAL_VELOCITY       1242
#define IDC_BUTTON_WATER_VELOCITY       1245
#define IDC_EDIT_JOY_1                  1246
#define IDC_STATIC_WATER_PATH           1246
#define IDC_EDIT_JOY_2                  1247
#define IDC_COMBO_TEST_BLOCKS           1247
#define IDC_STATIC_WATER_PATH2          1247
#define IDC_EDIT_JOY_3                  1248
#define IDC_STATIC_MATERIAL_PATH        1248
#define IDC_EDIT_MAX_TIMEBASE           1249
#define IDC_EDIT_JOY_4                  1249
#define IDC_STATIC_MATERIAL_PATH2       1249
#define IDC_EDIT_JOY_5                  1250
#define IDC_EDITID                      1250
#define IDC_EDIT_JOY_6                  1251
#define IDC_EDIT_JOY_7                  1252
#define IDC_EDIT_JOY_8                  1253
#define IDC_EDIT_JOY_9                  1254
#define IDC_EDIT_JOY_10                 1255
#define IDC_EDIT_ID                     1256
#define IDC_STATIC_VIEW_MANIP           1259
#define IDC_EDIT_GATE_INT_THRESHOLD     1262
#define IDC_SPIN_GATE_INT_THRESH        1263
#define IDC_COMBO_PMAC_TYPE             1266
#define IDC_EDIT_TIMS_STARTTHRESH       1266
#define IDC_EDIT_TX_COMMAND             1267
#define IDC_EDIT_TIMS_STOPTHRESH        1267
#define IDC_PROGRESS_DOWNLOAD           1268
#define IDC_BUTTON_INTERRUPTS           1269
#define IDC_EDIT_AMPLITUDE              1271
#define IDC_COMBO_AXIS                  1271
#define IDC_STATIC_IX30                 1272
#define IDC_STATIC_IX31                 1273
#define IDC_STATIC_IX32                 1274
#define IDC_STATIC_IX33                 1275
#define IDC_STATIC_IX34                 1276
#define IDC_CHECK_MUST_HOME             1277
#define IDC_EDIT_IX30                   1277
#define IDC_EDIT_IX31                   1278
#define IDC_EDIT_IX32                   1279
#define IDC_EDIT_IX33                   1280
#define IDC_EDIT_IX34                   1281
#define IDC_EDIT_IX35                   1282
#define IDC_EDIT_DAC_BLANKING           1282
#define IDC_STATIC_IX35                 1283
#define IDC_EDIT_DAC_THRESHOLD          1283
#define IDC_COMBO_TRAJECTORY            1284
#define IDC_SPIN_DAC_BLANKING           1284
#define IDC_STATIC_TRAJ0                1285
#define IDC_SPIN_DAC_THRESHOLD          1285
#define IDC_CHECK_GRATICULE_OFF_ON      1286
#define IDC_STATIC_TRAJ1                1286
#define IDC_COMBO_GATE_DELAY_UNITS      1287
#define IDC_STATIC_TRAJ2                1287
#define IDC_COMBO_GATE_WIDTH_UNITS      1288
#define IDC_STATIC_TRAJ3                1288
#define IDC_COMBO_TRACE_DELAY_UNITS     1289
#define IDC_EDIT_TRAJ0                  1289
#define IDC_COMBO_TRACE_WIDTH_UNITS     1290
#define IDC_EDIT_TRAJ1                  1290
#define IDC_EDIT_TRAJ2                  1291
#define IDC_EDIT_SCREEN_WIDTH           1291
#define IDC_EDIT_TRAJ3                  1292
#define IDC_EDIT_STEP_ZOOM_FACTOR       1292
#define IDC_EDIT_STEP_NUMBER            1293
#define IDC_BUTTON_DO                   1293
#define IDC_SPIN_STEP_NUMBER            1294
#define IDC_EDIT_GENERAL_INPUT          1294
#define IDC_BUTTON_STEP                 1295
#define IDC_EDIT_GENERAL_OUTPUT         1295
#define IDC_COMBO_TRIGGER_MODE          1296
#define IDC_CHECK_REFRESH               1296
#define IDC_EDIT_RUNNING                1297
#define IDC_COMBO_AMP_PRIORITY          1297
#define IDC_EDIT_BRIDGE                 1298
#define IDC_COMBO_THICK_PRIORITY        1298
#define IDC_COMBO_BRIDGE                1299
#define IDC_COMBO_COMPONENT             1301
#define IDC_CHECK_PR30                  1302
#define IDC_BUTTON_BODGE                1303
#define IDC_COMBO_NUMBERTIMESLOTS       1304
#define IDC_CHECK_WORKAREAS             1305
#define IDC_EDIT_X_SEP                  1308
#define IDC_EDIT_Y_SEP                  1309
#define IDC_COMBO_MOVEPROBE             1310
#define IDC_BUTTON_MOVEPROBEHERE        1311
#define IDC_COMBO_PROBENUMBER           1312
#define IDC_COMBO_PRIMARY_IMAGE         1313
#define IDC_COMBO_LOGICAL_RULES         1314
#define IDC_CHECK_TIME0                 1315
#define IDC_CHECK_TIME1                 1316
#define IDC_CHECK_TIME2                 1317
#define IDC_EDIT_TANK_ZERO              1323
#define IDC_EDIT_SAFE_POS               1323
#define IDC_BUTTON_TANK_ZERO_HERE       1324
#define IDC_BUTTON_READ_PMAC            1325
#define IDC_EDIT_NAME                   1326
#define IDC_EDIT_PASSWORD               1327
#define IDC_EDIT_ATP_MAX_THRESHOLD      1331
#define IDC_SPIN_ATP_MAX_THRESHOLD      1332
#define IDC_COMBO_TIMS_MODE             1333
#define IDC_SPIN_TIMS_WIDTH             1335
#define IDC_SPIN_TIMS_STARTTHRESH       1336
#define IDC_SPIN_TIMS_STOPTHRESH        1337
#define IDC_COMBO_TIMS_NUMBER           1342
#define IDC_SPIN_GATE_DELAY             1343
#define IDC_SPIN_GATE_WIDTH             1344
#define IDC_BUTTON_HMZ                  1345
#define IDC_COMBO_JOYSTICK_SOURCE       1345
#define IDC_STATIC_PASSED_COLOR         1346
#define IDC_STATIC_FAILED_COLOR         1347
#define IDC_BUTTON_MOVETOWATERPATH      1348
#define IDC_EDIT_DEFECTTHRESHOLD        1349
#define IDC_SPIN_DEFECTTHRESHOLD        1350
#define IDC_CHECK_STOPONDEFECT          1351
#define IDC_CHECK_ELASTICGATE           1352
#define IDC_EDIT_GATE_FIR               1353
#define IDC_CHECK_ULTRASONICS           1353
#define IDC_SPIN_GATE_FIR               1354
#define IDC_CHECK_PALETTES              1354
#define IDC_EDIT_TIMS_FIR               1355
#define IDC_CHECK_SCAN_DIMENSIONS       1355
#define IDC_CHECK_PR20                  1356
#define IDC_SPIN_TIMS_FIR               1356
#define IDC_CHECK_PROBEDETAILS          1356
#define IDC_CHECK_PR50                  1357
#define IDC_BUTTON_SENTENCE_FONT        1357
#define IDC_CHECK_PL15                  1358
#define IDC_COMBO_FILELISTINGSTYLE      1358
#define IDC_CHECK_PR15                  1359
#define IDC_EDIT_FILENAME               1359
#define IDC_COMBO_ROTATE                1359
#define IDC_CHECK_ATP_GPD0              1360
#define IDC_CHECK_ATP_GPD1              1361
#define IDC_CHECK_ATP_TIMS0             1362
#define IDC_CHECK_OPERATOR              1362
#define IDC_CHECK_ADC100                1363
#define IDC_CHECK_DATE                  1363
#define IDC_CHECK_ATP_TIMS1             1364
#define IDC_CHECK_BATCH                 1364
#define IDC_EDIT_BLANKING               1365
#define IDC_CHECK_ATP_GPD2              1365
#define IDC_CHECK_COMPONENT_ID          1365
#define IDC_SPIN_BLANKING               1366
#define IDC_CHECK_ATP_GPD3              1366
#define IDC_CHECK_STANDARD              1366
#define IDC_EDIT_DELAY                  1367
#define IDC_CHECK_SETUP_FILENAME        1367
#define IDC_EDIT_NEAR_DEADZONE          1368
#define IDC_EDIT_FAR_DEAD_ZONE          1369
#define IDC_EDIT_MAX_WIDTH              1370
#define IDC_EDIT_MAX_THRESHOLD          1371
#define IDC_SPIN_NEAR_DEADZONE          1371
#define IDC_EDIT_MIN_THRESHOLD          1372
#define IDC_SPIN_FAR_DEADZONE           1372
#define IDC_SPIN_MAX_THRESHOLD          1373
#define IDC_SPIN_MAX_WIDTH              1373
#define IDC_SPIN_MIN_THRESHOLD          1374
#define IDC_BUTTON_COPYTOALL            1374
#define IDC_EDIT_INTERFACE_THRESHOLD    1375
#define IDC_STATIC_TIMS_WIDTH           1375
#define IDC_SPIN_INTERFACE_THRESHOLD    1376
#define IDC_CHECK_GRATICULENUMBERS      1376
#define IDC_COMBO_TX                    1377
#define IDC_EDIT_TIMESLOT               1377
#define IDC_SPIN_TIMESLOT               1378
#define IDC_EDIT_PR20_ADDRS             1379
#define IDC_COMBO_STARTJOYSTICKPERCENTAGE 1379
#define IDC_EDIT_PR50_ADDRS             1380
#define IDC_EDIT_STORE_POS              1380
#define IDC_COMBO_LANGUAGE              1380
#define IDC_EDIT_MAILBOX_ADDRS          1381
#define IDC_BUTTON_STORE_COORDINATE     1381
#define IDC_EDIT_ATP_ADDRS              1382
#define IDC_EDIT_GPD_ADDRS0             1382
#define IDC_EDIT_ADC100_ADDRS           1383
#define IDC_COMBO_INTERLACED            1383
#define IDC_CHECK_MSC                   1384
#define IDC_EDIT_FURTHEST               1384
#define IDC_EDIT_MSC_ADDRS              1385
#define IDC_EDIT_NEAREST                1385
#define IDC_PROGRESS_AMPLITUDE          1386
#define IDC_EDIT_ADC100_MEM_ADDRS       1386
#define IDC_EDIT_XT_ERROR               1386
#define IDC_EDIT_GPD_ADDRS1             1387
#define IDC_BUTTON_Z_ERRORS             1387
#define IDC_CHECK_DSP                   1388
#define IDC_EDIT_Z_ERROR                1388
#define IDC_EDIT_DSP                    1389
#define IDC_EDIT_POS_0                  1389
#define IDC_EDIT_GPD_ADDRS2             1390
#define IDC_EDIT_POS_180                1390
#define IDC_EDIT_GPD_ADDRS3             1391
#define IDC_BUTTON_STORE_POS0           1391
#define IDC_EDIT_TIMS_ADDRS0            1392
#define IDC_BUTTON_STORE_POS180         1392
#define IDC_EDIT_TIMS_ADDRS1            1393
#define IDC_EDIT_RESULT                 1393
#define IDC_EDIT_POS_270                1394
#define IDC_EDIT_POS_90                 1395
#define IDC_BUTTON_STORE_POS90          1396
#define IDC_BUTTON_STORE_POS270         1397
#define IDC_COMBO_VOLUME_MODE           1398
#define IDC_COMBO_NORMALIZE_AXES        1398
#define IDC_EDIT_PRE_TRIGGER            1399
#define IDC_BUTTON_IMPLEMENT            1399
#define IDC_EDIT_POST_TRIGGER           1400
#define IDC_STATIC_AXIS0                1400
#define IDC_SPIN_PRE_TRIGGER            1401
#define IDC_STATIC_AXIS1                1401
#define IDC_SPIN_POST_TRIGGER           1402
#define IDC_EDIT_AXIS0                  1402
#define IDC_EDIT_AXIS1                  1403
#define IDC_EDIT_SHIFTLINE              1404
#define IDC_COMBO_RX                    1405
#define IDC_EDIT_HIGHLIGHT              1405
#define IDC_SLIDER_EDGE                 1406
#define IDC_EDIT_PAGE_PERCENT           1407
#define IDC_SPIN_HIGHTLIGHTLINE         1408
#define IDC_SPIN_SHIFTLINE              1409
#define IDC_CHECK_GATE0                 1410
#define IDC_STATIC_SEARCH_FIELD         1411
#define IDC_STATIC_TEMP                 1412
#define IDC_USLBARCTRL                  1413
#define IDC_COMBO_COLLECTVOLUME         1414
#define IDC_EDIT_PEAK_RESULT            1414
#define IDC_EDIT_GENERAL                1415
#define IDC_STATIC_MODE                 1416
#define IDC_BUTTON_COPY_COORDS          1417
#define IDC_CHECK_HIGHLIGHT             1418
#define IDC_EDIT_ADC_MEMORY_ADDRS       1419
#define IDC_BUTTON_NOMINALX             1420
#define IDC_EDIT_SERIAL0                1421
#define IDC_EDIT_SERIAL1                1422
#define IDC_COMBO_ADC_TYPE              1422
#define IDC_EDIT_SERIAL2                1423
#define IDC_EDIT_SERIAL3                1424
#define IDC_EDIT_SERIAL4                1425
#define IDC_EDIT_SERIAL5                1426
#define IDC_EDIT_SERIAL6                1427
#define IDC_EDIT_SERIAL7                1428
#define IDC_EDIT_DB                     1429
#define IDC_USLBARCTRL_FREQUENCY        1431
#define IDC_COMBO_PREAMP_MODE           1433
#define IDC_EDIT_MAX_Z_CHANGE           1434
#define IDC_EDIT_MAX_XTIP_CHANGE        1435
#define IDC_CHECK_PROBE_NUMBER          1436
#define IDC_CHECK_ENABLE_RING           1437
#define IDC_STATIC_SLIDER               1438
#define IDC_COMBO_AMPLIFIER             1439
#define IDC_BUTTON_NORMAL_ZERO          1439
#define IDC_STATIC_VERSION              1440
#define IDC_EDITVERTICAL_GRATICULE      1441
#define IDC_CHECK_GATE_0                1444
#define IDC_CHECK_GATE_1                1445
#define IDC_CHECK_GATE_2                1446
#define IDC_CHECK_GATE_3                1447
#define IDC_CHECK_GATE_4                1448
#define IDC_CHECK_GATE_5                1449
#define IDC_CHECK_GATE_6                1450
#define IDC_CHECK_GATE_7                1451
#define IDC_CHECK_WATERPATH             1455
#define IDC_CHECK_GATE_AMP              1456
#define IDC_EDIT_TEXT_SIZE              1459
#define IDC_COMBO_GATE_TIMESLOT_ACTION  1459
#define IDC_SPIN_TEXT_SIZE              1460
#define IDC_COMBO_ORIENTATION           1460
#define IDC_EDIT_X                      1461
#define IDC_EDIT_Y                      1462
#define IDC_EDIT_Z                      1463
#define IDC_EDIT_XT                     1464
#define IDC_EDIT_YT                     1465
#define IDC_EDIT_R                      1466
#define IDC_STATIC_Y                    1467
#define IDC_STATIC_X                    1468
#define IDC_EDIT_MATERIAL_DENSITY       1469
#define IDC_STATIC_Z                    1469
#define IDC_STATIC_XT                   1470
#define IDC_STATIC_YT                   1471
#define IDC_STATIC_R                    1472
#define IDC_USLBARCTRL_DELAY_WIDTH      1473
#define IDC_STATIC_Z2                   1473
#define IDC_CHECK_COPY_TO_ALL_TS        1474
#define IDC_EDIT_Z2                     1474
#define IDC_CHECK_METALPATH             1475
#define IDC_CHECK_COLLECT_ALL_TS        1475
#define IDC_STATIC_XT2                  1475
#define IDC_CHECK_COLLECT_ALLTS         1476
#define IDC_EDIT_XT2                    1476
#define IDC_STATIC_YT2                  1477
#define IDC_CHECK_LOCK_ALL_SLIDERS      1478
#define IDC_EDIT_YT2                    1478
#define IDC_BUTTON_ROTATE_POS           1480
#define IDC_EDIT_DETAILS_0              1481
#define IDC_EDIT_DETAILS_1              1482
#define IDC_COMBO_DAC_BLANKING_UNITS    1482
#define IDC_EDIT_DETAILS_2              1483
#define IDC_COMBO_DAC_DELAY_UNITS       1483
#define IDC_EDIT_DETAILS_3              1484
#define IDC_STATIC_ALARM                1485
#define IDC_EDIT_DETAILS_4              1485
#define IDC_STATIC_ALARM_TEXT           1486
#define IDC_EDIT_DETAILS_5              1486
#define IDC_EDIT_DETAILS_6              1487
#define IDC_CHECK_BW_OFF_ON             1489
#define IDC_EDIT_DIRCTORY               1491
#define IDC_EDIT_LOG_GAIN               1493
#define IDC_STATIC_DIRECTORY            1493
#define IDC_SPIN_LOG_GAIN               1494
#define IDC_COMBO_POST_FILTER           1495
#define IDC_EDIT_DELTA                  1495
#define IDC_EDIT_LIN_GAIN               1496
#define IDC_EDIT_DIAMETER               1496
#define IDC_SPIN_LIN_GAIN               1497
#define IDC_COMBO_FILTER_TYPE           1498
#define IDC_COMBO_BW_GATE               1499
#define IDC_EDIT_CENTRE_FREQ            1500
#define IDC_SPIN_CENTRE_FREQ            1501
#define IDC_COMBO_RECTIFIER_MODE        1502
#define IDC_EDIT_RECTIFIER_DECAY        1503
#define IDC_SPIN_RECTIFIER_DECAY        1504
#define IDC_COMBO_DAC_MODE              1506
#define IDC_CHECK_ACQIRIS               1508
#define IDC_LIST_DAC_LIST               1510
#define IDC_EDIT_INDEX                  1510
#define IDC_STATIC_BLANKING_TEXT        1511
#define IDC_COMBO_DAC_TRIGGER_MODE      1512
#define IDC_COMBO_IMAGE                 1515
#define IDC_STATIC_GATE_COLOR_0         1516
#define IDC_COMBO_POSITION_MODE         1516
#define IDC_STATIC_GATE_COLOR_1         1517
#define IDC_BUTTON_ZERO                 1517
#define IDC_STATIC_GATE_COLOR_2         1518
#define IDC_CHECK_VERIFY_FIND_PEEK      1518
#define IDC_STATIC_GATE_COLOR_3         1519
#define IDC_COMBO_LF_POINT              1519
#define IDC_CHECK_VERIFY_STORE_PEEK     1519
#define IDC_COMBOAXIS                   1519
#define IDC_STATIC_GATE_COLOR_4         1520
#define IDC_CHECK_VERIFY_STORE_DEPTH    1520
#define IDC_EDITVALUE                   1520
#define IDC_STATIC_GATE_COLOR_5         1521
#define IDC_COMBOTYPE                   1521
#define IDC_STATIC_GATE_COLOR_6         1522
#define IDC_APPLY                       1522
#define IDC_STATIC_GATE_COLOR_7         1523
#define IDC_RETURN                      1523
#define IDC_STATIC_TRACE_COLOR          1524
#define IDC_STATIC_BK_COLOR             1525
#define IDC_EDIT_X_MOVE_CONSTANT        1525
#define IDC_STATIC_GRATICULE_COLOR      1526
#define IDC_EDIT_Y_MOVE_CONSTANT        1526
#define IDC_STATIC_DAC_COLOR            1527
#define IDC_STATIC_POS_PHASE_COLOR      1527
#define IDC_EDIT1                       1527
#define IDC_STATIC_NEG_PHASE_COLOR      1528
#define IDC_STATIC_LINE_COLOUR          1528
#define IDC_EDIT_HOLE_TYPE              1528
#define IDC_EDIT_Y_MAX                  1528
#define IDC_EDIT_PT_1                   1528
#define IDC_EDIT_Y_JOY                  1528
#define IDC_COMBO_GREATER_LESS          1529
#define IDC_EDIT_WAVE_TYPE              1529
#define IDC_EDIT_XMAX                   1529
#define IDC_EDIT_Z_JOY                  1529
#define IDC_EDIT_ALLOY_GRADE            1530
#define IDC_EDIT_X_MIN                  1530
#define IDC_EDIT_S_JOY                  1530
#define IDC_EDIT_HOLE_SIZE              1531
#define IDC_COMBO_RULE_0                1532
#define IDC_BUTTON_SLOPE_0              1533
#define IDC_EDIT_RULE_0                 1534
#define IDC_SPIN_RULE_0                 1535
#define IDC_EDIT_FFT_GAIN               1537
#define IDC_CHECK_RULE_0                1537
#define IDC_COMBO_RULE_1                1538
#define IDC_COMBO_PALETTE               1538
#define IDC_SPIN_FFT_GAIN               1539
#define IDC_BUTTON_SLOPE_1              1539
#define IDC_EDIT_DETAILS_7              1539
#define IDC_EDIT_RULE_1                 1540
#define IDC_EDIT_DETAILS_8              1540
#define IDC_COMBO_FFT_RESOLVABLE        1541
#define IDC_SPIN_RULE_1                 1541
#define IDC_EDIT_DETAILS_9              1541
#define IDC_COMBO_RF_SOURCE             1542
#define IDC_BUTTON_AUTO_BACKWALL        1542
#define IDC_CHECK_RULE_1                1543
#define IDC_COMBO_RULE_2                1544
#define IDC_BUTTON_SLOPE_2              1545
#define IDC_EDIT_RULE_2                 1546
#define IDC_SPIN_RULE_2                 1547
#define IDC_CHECKVERIFY_STOR_COORD      1548
#define IDC_CHECK_RULE_2                1549
#define IDC_CHECK_VERIFY_DO_MICRO       1550
#define IDC_EDIT_TEST_BLOCK_NUMBER      1551
#define IDC_CHECK_C_SCAN                1552
#define IDC_CHECK_DEFECT_TABLE          1553
#define IDC_COMBO_FOLLOWING_MODE        1554
#define IDC_COMBO_VARIABLE              1555
#define IDC_EDIT_STATUS_8               1557
#define IDC_EDIT_POSITION_9             1558
#define IDC_EDIT_DECODE_1               1559
#define IDC_EDIT_DECODE_2               1560
#define IDC_EDIT_DECODE_3               1561
#define IDC_EDIT_DECODE_4               1562
#define IDC_EDIT_DECODE_5               1563
#define IDC_EDIT_DECODE_6               1564
#define IDC_BUTTONZERO_X                1565
#define IDC_EDIT_DECODE_7               1565
#define IDC_BUTTONZERO_Y                1566
#define IDC_EDIT_DECODE_8               1566
#define IDC_BUTTONZERO_Z                1567
#define IDC_EDIT_DECODE_9               1567
#define IDC_EDIT_RX_ARRAY               1568
#define IDC_BUTTONZERO_XT               1568
#define IDC_EDIT_DECODE_10              1568
#define IDC_BUTTONZERO_YT               1569
#define IDC_BUTTON_APPLY                1569
#define IDC_EDIT_OFFSET                 1570
#define IDC_COMBO_PR30_TRIGGER          1571
#define IDC_EDIT_Y_MIN                  1571
#define IDC_COMBO_HT_OFF_ON             1572
#define IDC_BUTTON_Y_MIN                1572
#define IDC_BUTTON_X_MIN                1573
#define IDC_COMBO_PALETTE_TYPE          1573
#define IDC_BUTTON_X_MAX                1574
#define IDC_CHECK_GATE_RESULT           1574
#define IDC_BUTTON_Y_MAX                1575
#define IDC_EDIT_PLATE_SIZE_SPEED       1575
#define IDC_COMBO_MANIPULATOR_TYPE      1576
#define IDC_COMBO_PEEK_FIND_MODE        1577
#define IDC_EDIT_DETAILS_10             1579
#define IDC_BUTTON_LASTSETTINGS         1580
#define IDC_EDIT_DETAILS_25             1580
#define IDC_EDIT_NUMBER_OF_ENTRIES      1581
#define IDC_EDIT_DETAILS_21             1581
#define IDC_SPIN_NUMBER_OF_ENTRIES      1582
#define IDC_EDIT_DETAILS_22             1582
#define IDC_EDIT_DETAILS_20             1583
#define IDC_EDIT_DETAILS_23             1584
#define IDC_EDIT_DETAILS_24             1585
#define IDC_COMBO_GRAPH_TYPE            1586
#define IDC_EDIT_DETAILS_26             1586
#define IDC_COMBO_WHICH_GATE            1587
#define IDC_COMBO_PR30_PULSER           1587
#define IDC_CHECK_CALIBRATION_RESULTS   1587
#define IDC_BUTTON_PT_0                 1588
#define IDC_BUTTON_MAKE_IT_SO           1589
#define IDC_BUTTON_PT_1                 1589
#define IDC_EDIT_PT_0                   1590
#define IDC_BUTTON_GOTO_MID_PT          1591
#define IDC_EDIT_REDUCED_GAIN           1592
#define IDC_BUTTON_RESET_MAILBOX        1593
#define IDC_BUTTON_BUBBLE_POS           1593
#define IDC_EDIT_BUBBLE_REMOVAL_POS     1594
#define IDC_CHECK_GRATICULE             1595
#define IDC_CHECK_CENTER                1596
#define IDC_EDIT_PROCESS_TIME0          1597
#define IDC_CHECKBEAM_WIDTH             1597
#define IDC_EDIT_PROCESS_TIME1          1598
#define IDC_EDIT_DB_DROP                1598
#define IDC_EDIT_PRINT_FONT_SIZE        1599
#define IDC_EDIT_GAIN_0                 1600
#define IDC_STATIC_LEFT                 1600
#define IDC_SPIN_GAIN_0                 1601
#define IDC_STATIC_RIGHT                1601
#define IDC_EDIT_CAPTION                1602
#define IDC_EDIT_FONT                   1603
#define IDC_EDIT_NUMBER_OF_PROBES       1603
#define IDC_BUTTON_FONT                 1604
#define IDC_BUTTON_REFRESH              1604
#define IDC_EDIT_X_JOY                  1605
#define IDC_EDIT_STR                    1613
#define IDC_EDIT_LINE_WIDTH             1615
#define IDC_SPIN_LINE_WIDTH             1616
#define IDC_STATIC_LINE_COLOR           1617
#define IDC_COMBO_LINE_STYLE            1618
#define IDC_COMBO_GATE                  1619
#define IDC_COMBO_BORDER                1620
#define IDC_COMBO_HOLE_GATE             1620
#define IDC_EDIT_BORDER_WIDTH           1621
#define IDC_SPIN_BORDER_WIDTH           1622
#define IDC_STATIC_BORDER_COLOR         1623
#define IDC_CHECK_LEFT                  1624
#define IDC_CHECK_RIGHT                 1625
#define IDC_CHECK_TOP                   1626
#define IDC_CHECK_BOTTOM                1627
#define IDC_BUTTON_GRATICULE_FONT       1628
#define IDC_COMBO_DATE_FORMAT           1629
#define IDC_COMBO_WHICH_DATE            1630
#define IDC_COMBO_WHICH_LIST            1632
#define IDC_CHECK_CAPTION_LEFT          1639
#define IDC_CHECK_CAPTION_RIGHT         1640
#define IDC_COMBO_CAPTION_POSITION      1649
#define IDC_EDIT_DELAY_CLK              1669
#define IDC_EDIT_CODE                   1683
#define IDC_COMBO_PR15_ADC_INPUT        1717
#define IDC_COMBO_PL15_ADC_INPUT        1718
#define IDC_COMBO_PR30_ADC_INPUT        1719
#define IDC_COMBO_DAC_ADC_INPUT         1720
#define IDC_BUTTON_ADC_RESET            1725
#define IDC_BUTTON_DSP_RESET            1726
#define IDC_CHECK_PHASE                 1811
#define IDC_COMBO_LOG_VERSION           1813
#define IDC_COMBO_LIN_VERSION           1814
#define IDC_COMBO_PR30_VERSION          1815
#define IDC_COMBO_NUMBER_TIMESLOTS      1917
#define IDC_STATIC_GROUP_0              1918
#define IDC_STATIC_TEXT_0               1919
#define IDC_STATIC_TEXT_1               1920
#define IDC_STATIC_TEXT_2               1921
#define IDC_COMBO_WHICH_TIMESLOT        1924
#define IDC_COMBO_DELAY_UNITS           1926
#define IDC_COMBO_WIDTH_UNITS           1927
#define IDC_COMBO_TRIGGER_SOURCE        1968
#define IDC_COMBO_FULLSCALE_RANGE       1969
#define IDC_EDIT_TRIGGER_THRESHOLD      1970
#define IDC_SPIN_TRIGGER_THRESHOLD      1971
#define IDC_SLIDER_OFFSET               1972
#define IDC_COMBO_PRF_SOURCE            1973
#define IDC_COMBO_TOF_MODE              1975
#define IDC_COMBO_ENABLE_DEVICE         1976
#define IDC_EDIT_INLINECOMMAND          1977
#define IDC_EDIT_RESPONCE               1978
#define IDC_LIST_VARIABLES              1979
#define IDC_EDIT_JUMPTO                 1981
#define IDC_EDIT_PROGRAM                1984
#define IDC_COMBO_AXIS_NUMBER           2054
#define IDC_LIST_VARIABLE               2055
#define IDC_EDIT_IRQ                    2056
#define IDC_CHECK_TIMESLOT              2057
#define IDC_CHECK_TOF_0                 2059
#define IDC_CHECK_TOF_1                 2060
#define IDC_CHECK_TOF_2                 2061
#define IDC_CHECK_TOF_3                 2062
#define IDC_CHECK_TOF_4                 2063
#define IDC_CHECK_TOF_5                 2064
#define IDC_CHECK_TOF_6                 2065
#define IDC_CHECK_TOF_7                 2066
#define IDC_COMBO_TOF_LAST              2067
#define IDC_COMBO_TOF                   2068
#define IDC_COMBO_TOF_FIRST             2069
#define IDC_COMBO_TEST                  2139
#define IDC_EDIT_TA                     2141
#define IDC_EDIT_TS                     2142
#define ID_VIEW_BACKWALLGATE            32774
#define ID_ZOOM_FULL                    32775
#define ID_ZOOM_PLATEOUTLINE            32776
#define ID_VIEW_LOGICALCOMBINATION      32779
#define ID_VIEW_BODY                    32780
#define ID_VIEW_IMAGE_0                 32780
#define ID_DEFECTS_THRESHOLDS           32782
#define ID_ZOOM_11ASPECTRATIO           32783
#define ID_OUTLINES_PLATE               32785
#define ID_OUTLINES_CUTOFF1             32786
#define ID_OUTLINES_CUTOFF2             32787
#define ID_OUTLINES_CUTOFF3             32788
#define ID_OUTLINES_MIDWALL             32789
#define ID_FILE_SAVE_BMP                32792
#define ID_DEFECTS_LISTTABLE            32794
#define ID_POPUP_ADD                    32795
#define ID_DEFECTS_DISPLAYCROSSES       32796
#define ID_POPUP_DELETE                 32797
#define ID_ULTRASONICS_TIMESLOTS        32798
#define ID_ULTRASONICS_OSCILLOSCOPE     32799
#define ID_ULTRASONICS_SAVE             32800
#define ID_ULTRASONICS_SAVEAS           32801
#define ID_ULTRASONICS_OPEN             32802
#define ID_ULTRASONICS_PROBE            32803
#define ID_ULTRASONICS_COMPONENT        32805
#define ID_ULTRASONICS_DACSENSITIVITY_CHECKSENSITVITY 32806
#define ID_ULTRASONICS_DACSENSITIVITY_TABLE 32807
#define ID_SCAN_DETAILS                 32808
#define ID_SCAN_DIMENSIONS              32809
#define ID_FILE_LOGON                   32810
#define ID_FILE_OPERATORS               32811
#define ID_MOTION_MOVETOZERO            32812
#define ID_MOTION_ORIGINFIND            32813
#define ID_MOTION_MOVETOPLACE           32814
#define ID_MOTION_MOVETOSAFE            32815
#define ID_SYSTEM_GENERAL               32816
#define ID_SYSTEM_DEVICERESOURCES       32817
#define ID_SYSTEM_AXES                  32818
#define ID_SYSTEM_CARDSADDRESSES        32819
#define ID_VIEW_BARGRAPHS               32820
#define ID_PALETTE_OPEN                 32821
#define ID_PALETTE_SAVE                 32822
#define ID_PALETTE_SAVEAS               32823
#define ID_PALETTE_EDIT                 32824
#define ID_PALETTE_ADD                  32825
#define ID_PALETTE_DELETE               32826
#define ID_BUTTON_EMERENCY_STOP         32827
#define ID_BUTTON_JOYSTICK              32828
#define ID_BUTTON_PLANAR                32829
#define ID_BUTTON_NORMAL                32830
#define ID_BUTTON_LOWGAIN               32831
#define ID_BUTTON_HIGHGAIN              32832
#define ID_SYSTEM_PMAC                  32833
#define ID_SYSTEM_IVARIABLES            32834
#define ID_MOTION_ORIGINFIND_ALL        32835
#define ID_MOTION_ORIGINFIND_X          32836
#define ID_MOTION_ORIGINFIND_Y          32837
#define ID_MOTION_ORIGINFIND_Z          32838
#define ID_MOTION_ORIGINFIND_XTIP       32839
#define ID_MOTION_ORIGINFIND_YTIP       32840
#define ID_MOTION_ORIGINFIND_R          32841
#define ID_MOTION_ORIGINFIND_M          32842
#define ID_SYSTEM_HEXDUMP               32843
#define ID_MOTION_MOVETO_SAFE           32844
#define ID_MOTION_MOVETO_PLACE          32845
#define ID_MOTION_MOVETO_ZERO           32846
#define ID_DACTABLE_STOREPOS            32847
#define ID_DACTABLE_STOREGATES          32848
#define ID_DACTABLE_STOREAMPLITUDE      32849
#define ID_DACTABLE_STOREALL            32850
#define ID_DACTABLE_GOTO                32851
#define ID_BUTTON_BODY_GATE             32852
#define ID_BUTTON_BW_GATE               32853
#define ID_BUTTON_THICKNESS_GATE        32854
#define ID_BUTTON_WATERPATH_GATE        32855
#define ID_SYSTEM_ULTRASONICS           32856
#define ID_BUTTON_TVG                   32857
#define ID_SYSTEM_FLUKE                 32858
#define ID_SYSTEM_ADC200                32859
#define ID_MOVETO_HERE                  32860
#define ID_MOVETO_START                 32861
#define ID_MOVETO_CENTER                32862
#define ID_MOVETO_FINISH                32863
#define ID_MOVETO_SAFE                  32864
#define ID_MOVETO_ZERO                  32865
#define ID_SCAN_START                   32866
#define ID_FILE_SENTENCE                32867
#define ID_POPUP_MOVETO                 32868
#define ID_POPUP_COLOURS                32869
#define ID_SCAN_BEAMPROFILE             32870
#define ID_MOVETO_SCRIBE                32871
#define ID_FILE_CLEAR                   32874
#define ID_FILE_REPORTPRINT             32875
#define ID_SCAN_MICROSCAN               32876
#define ID_VIEW_NOTES                   32877
#define ID_DACTABLE_SETGATES            32878
#define ID_DEFECTS_GOTO                 32879
#define ID_DEFECTS_DELETE               32880
#define ID_DEFECTS_ACCEPTDEPTH          32881
#define ID_ZOOM_100                     32882
#define ID_ZOOM_150                     32883
#define ID_ZOOM_200                     32884
#define ID_DEFECTS_DELETEAGROUP         32885
#define ID_DEFECTS_SCRIBE               32887
#define ID_SYSTEM_DATABASEOPTIONS       32888
#define ID_POPUP_ADD_ATMOUSE            32889
#define ID_POPUP_ADD_ELEMENT            32890
#define ID_OSCILLOSCOPE_PRINT           32891
#define ID_DEFECTS_OSCILLOSCOPE_SAVE    32893
#define ID_DEFECTS_OSCILLOSCOPE_REVIEW  32894
#define ID_OSCILLOSCOPE_NEXT            32895
#define ID_OSCILLOSCOPE_PREVIOUS        32896
#define ID_SYSTEM_TANK                  32897
#define ID_POPUP_SENTENCE               32898
#define ID_ULTRASONICS_IMPORTDOSSETUP   32899
#define ID_POPUP_ANNOTATE               32900
#define ID_FILE_OPEN_PLATE              32901
#define ID_FILE_OPEN_STANDARD           32902
#define ID_ZOOM_VARIABLES               32903
#define ID_SYSTEM_VARIABLES_I           32904
#define ID_SYSTEM_VARIABLES_M           32905
#define ID_BACKUP_SAVE_MOTORSENCODERS   32906
#define ID_BACKUP_RESTORE_MOTORSENCODERS 32907
#define ID_SYSTEM_PMAC_GENERAL          32908
#define ID_SYSTEM_PMAC_TUNING           32909
#define ID_MOVETO_STORE_WORKAREALEFT_TOPLEFT 32912
#define ID_MOVETO_STORE_WORKAREALEFT_BOTTOMRIGHT 32913
#define ID_MOVETO_STORE_WORKAREARIGHT_TOPLEFT 32914
#define ID_MOVETO_STORE_WORKAREARIGHT_BOTTOMRIGHT 32915
#define ID_SYSTEM_JOYSTICKS             32916
#define ID_MOVETO_STORE_SAFEPOSITION    32917
#define ID_RBDACMENU_CLEAREVERYTHING    32918
#define ID_RBDACMENU_CLEARALLGAINS      32919
#define ID_RBDACMENU_DELETEPT           32920
#define ID_SCOPE_DISPLAYDACPOINTS       32921
#define ID_SCOPE_DACREFAMPLITUDE        32922
#define ID_SCOPE_STOREDACPOINT          32923
#define ID_SCOPE_DELETEDACPOINT         32924
#define ID_SYSTEM_DIRECTORIES           32925
#define ID_BUTTON_MOVETOSAFEHEIGHT      32926
#define ID_SETUPS_OPEN                  32929
#define ID_SETUPS_SAVEAS                32930
#define ID_TEMPLATE_NEW                 32931
#define ID_TEMPLATE_OPEN                32932
#define ID_TEMPLATE_SAVEAS              32933
#define ID_TEMPLATE_PAGESETUP           32934
#define ID_TEMPLATE_PRINT               32935
#define ID_EDIT_FONT                    32936
#define ID_REPORT_TEXT                  32938
#define ID_REPORT_IMAGE                 32939
#define ID_REPORT_LEFTALIGN             32940
#define ID_REPORT_RIGHTALIGN            32941
#define ID_REPORT_CENTRE                32942
#define ID_REPORT_LINEHORIZONTAL        32943
#define ID_REPORT_LINEVERTICAL          32944
#define ID_REPORT_RECTANGLE             32945
#define ID_BUTTON_POINTER               32946
#define ID_BUTTON_LINE                  32947
#define ID_BUTTON_RECTANGLE             32948
#define ID_BUTTON_IMAGE                 32949
#define ID_BUTTON_TEXT                  32950
#define ID_BUTTON_ERASE                 32951
#define ID_BUTTON_MOVE                  32952
#define ID_BUTTON_DATE                  32953
#define ID_BUTTON_LIST                  32954
#define ID_BUTTON_BARGRAPH              32955
#define ID_MAINFRAME_DISPLAYTANKCOORDINATES 32956
#define ID_MAINFRAME_DISPLAYPROBECOORDINATES 32957
#define ID_VIEW_POSITION                32958
#define ID_MOTION_SQUINT                32960
#define ID_POPUP_ARROW                  32961
#define ID_VIEW_COMPONENTID             32962
#define ID_VIEW_ANNOTATION              32963
#define ID_BUTTON32964                  32964
#define ID_BEAM_RULER                   32966
#define ID_VIEW_ALLTRACES               32967
#define ID_VIEW_PEAKTRACES              32968
#define ID_VIEW_GRATICULE               32969
#define ID_VIEW_DBGRATICULE             32970
#define ID_ULTRASONICS_SPECTRUMANALYZER 32971
#define ID_BUTTON_STOP_SCAN             32972
#define ID_BUTTON_START_SCAN            32973
#define ID_BUTTON_Z_HEIGHT              32974
#define ID_SCOPE_SAVEASBMP              32977
#define ID_MOVETO_STORE_WORKAREALEFT_TOP 32978
#define ID_MOVETO_STORE_WORKAREALEFT_BOTTOM 32979
#define ID_MOVETO_STORE_WORKAREALEFT_LEFT 32980
#define ID_MOVETO_STORE_WORKAREALEFT_RIGHT 32981
#define ID_MOVETO_STORE_WORKAREARIGHT_TOP 32982
#define ID_MOVETO_STORE_WORKAREARIGHT_BOTTOM 32983
#define ID_MOVETO_STORE_WORKAREARIGHT_LEFT 32984
#define ID_MOVETO_STORE_WORKAREARIGHT_RIGHT 32985
#define ID_POPUP_ARROW_ADD              32987
#define ID_POPUP_ARROW_DELEET           32988
#define ID_SCOPE_LOCKDELAYTOZ           32989
#define ID_SCOPE_STARTRECORDING         32990
#define ID_SCOPE_STOPRECORDING          32991
#define ID_SCOPE_PLAYRECORDING          32992
#define ID_SCOPE_PALETTE                32993
#define ID_SCOPE_SCALEBOTTOM            32994
#define ID_SCOPE_SCALELEFT              32995
#define ID_SCOPE_SCALERIGHT             32996
#define ID_SCOPE_SCALETOP               32997
#define ID_SCOPE_DRAWMODEVECTOR         32998
#define ID_SCOPE_DRAWMODEDOTS           32999
#define ID_SCOPE_STATISTICS             33000
#define ID_SCOPE_CURRENTTIMESLOT        33001
#define ID_SCOPE_SLOT1                  33002
#define ID_SCOPE_SLOT2                  33003
#define ID_SCOPE_SLOT3                  33004
#define ID_SCOPE_SLOT4                  33005
#define ID_SCOPE_SLOT5                  33006
#define ID_SCOPE_SLOT6                  33007
#define ID_SCOPE_SLOT7                  33008
#define ID_SCOPE_SLOT8                  33009
#define ID_SYSTEM_ACQIRIS               33010
#define ID_GATES_COPYNAMESTOALLTIMESLOTS 33011
#define ID_MOTION_ORIGINFIND_ROTATE     33013
#define ID_VIEW_DIALOGBAR               33014
#define IDS_TIMESLOT_0                  33204
#define IDS_TIMESLOT_1                  33205
#define IDS_TIMESLOT_2                  33206
#define IDS_TIMESLOT_3                  33207
#define IDS_TIMESLOT_4                  33208
#define IDS_TIMESLOT_5                  33209
#define IDS_TIMESLOT_6                  33210
#define IDS_TIMESLOT_7                  33211
#define IDS_TIMS_BODY                   33212
#define IDS_TIMS_WATERPATH              33213
#define IDS_GPD_BODY                    33214
#define IDS_GPD_BACKWALL                33215
#define IDS_X_AXIS_DLG                  33216
#define IDS_Y_AXIS_DLG                  33217
#define IDS_Z_AXIS_DLG                  33218
#define IDS_Z1_AXIS_DLG                 33218
#define IDS_XT_AXIS_DLG                 33219
#define IDS_XT1_AXIS_DLG                33219
#define IDS_YT_AXIS_DLG                 33220
#define IDS_YT1_AXIS_DLG                33220
#define IDS_R_AXIS_DLG                  33221
#define IDS_M_AXIS_DLG                  33222
#define ID_INDICATOR_OPERATOR           33223
#define ID_INDICATOR_XPOS               33224
#define ID_INDICATOR_YPOS               33225
#define ID_INDICATOR_ULFILENAME         33226
#define ID_INDICATOR_XTPOS              33227
#define ID_INDICATOR_YTPOS              33228
#define ID_INDICATOR_ZPOS               33229
#define ID_INDICATOR_NORMAL             33230
#define ID_INDICATOR_HDUSPACE           33231
#define ID_INDICATOR_PROBESERIALNUMBER  33232
#define IDS_mV                          33233
#define IDS_Div                         33234
#define IDS_uS                          33235
#define IDS_mm_Water                    33236
#define IDS_mm_Material                 33237
#define IDS_Never                       33238
#define IDS_hours                       33239
#define IDS_No                          33240
#define IDS_Yes                         33241
#define IDS_Single_Bridge_Left          33242
#define IDS_Single_Bridge_Right         33243
#define IDS_Double_Bridge               33244
#define IDS_Left                        33245
#define IDS_Right                       33246
#define IDS_Logical                     33247
#define IDS_Image                       33248
#define IDS_Loss_of_Interface_or_Gate   33249
#define IDS_Explorer                    33250
#define IDS_Verbose                     33251
#define IDS_Min                         33252
#define IDS_Max                         33253
#define IDS_Normal                      33254
#define IDS_Rotate_180                  33255
#define IDS_Mirror                      33256
#define IDS_Non_Mux                     33257
#define IDS_Multiplex                   33258
#define IDS_Blended                     33259
#define IDS_Block                       33260
#define IDS_Total                       33261
#define IDS_Window                      33262
#define IDS_All                         33263
#define IDS_Main_Bang                   33264
#define IDS_Interface                   33265
#define IDS_None                        33266
#define IDS_Raised                      33267
#define IDS_Sunken                      33268
#define IDS_Dont_Display                33269
#define IDS_Top_Left                    33270
#define IDS_Top_Centre                  33271
#define IDS_Top_Right                   33272
#define IDS_Bottom_Left                 33273
#define IDS_Bottom_Centre               33274
#define IDS_Bottom_Right                33275
#define IDS_Space                       33276
#define IDS_tab                         33277
#define IDS_Scan                        33278
#define IDS_Todays                      33279
#define IDS_Pass                        33280
#define IDS_Fail                        33281
#define IDS_Report                      33282
#define IDS_Present                     33283
#define IDS_Not_Present                 33284
#define IDS_Off                         33285
#define IDS_MB_Interface                33286
#define IDS_MB_Gate                     33287
#define IDS_Interface_Gate              33288
#define IDS_Edge                        33289
#define IDS_Peak                        33290
#define IDS_Rising                      33291
#define IDS_Falling                     33292
#define IDS_mm                          33293
#define IDS_Please_Select               33294
#define IDS_Body                        33295
#define IDS_Water_Path                  33296
#define IDS_Thickness                   33297
#define IDS_FIR                         33298
#define IDS_Average                     33299
#define IDS_Ultrasonics                 33300
#define IDS_Servo                       33301
#define IDS_Si6                         33302
#define IDS_Solid                       33303
#define IDS_Dot                         33304
#define IDS_Dashed                      33305
#define IDS_Dash_Dot                    33306
#define IDS_Dash_Dot_Dot                33307
#define IDS_Frame                       33308
#define IDS_Component_stats             33309
#define IDS_Defect_List                 33310
#define IDS_Multiple_Results            33311
#define IDS_Operator                    33312
#define IDS_Supervisor                  33313
#define IDS_Manufacturer                33314
#define IDS_General_M_Variables         33315
#define IDS_General_I_Variables         33316
#define IDS_Position_PLC                33317
#define IDS_Status_PLC                  33318
#define IDS_Joystick_PLC                33319
#define IDS_Origin_All                  33320
#define IDS_Origin                      33321
#define IDS_Major_Axes_MoveTo           33322
#define IDS_All_MoveTo                  33323
#define IDS_Normalize                   33324
#define IDS_PLCCs                       33325
#define IDS_Tank                        33326
#define IDS_Probe                       33327
#define IDS_Plates                      33328
#define IDS_Standard                    33329
#define IDS_Interlaced                  33330
#define IDS_Non_Interlaced              33331
#define IDS_Entire_Trace                33332
#define IDS_Dont_Collect                33333
#define IDS_Collect                     33334
#define IDS_Comm                        33335
#define IDS_Linear                      33336
#define IDS_Gain                        33337
#define IDS_Body_Gates                  33338
#define IDS_Bw_Gates                    33339
#define IDS_DAC                         33340
#define IDS_Pulse_Echo                  33341
#define IDS_Pitch_Catch                 33342
#define IDS_RF                          33343
#define IDS_Rectified                   33344
#define IDS_Logorithmic                 33345
#define IDS_WideBand                    33346
#define IDS_Low_Pass                    33347
#define IDS_Band_Pass_Narrow            33348
#define IDS_Band_Pass_Wide              33349
#define IDS_Positive                    33350
#define IDS_Negative                    33351
#define IDS_Full_Wave                   33352
#define IDS_Full                        33353
#define IDS_Step                        33354
#define IDS_Parabola                    33355
#define IDS_On                          33356
#define IDS_Are_you_allowed_to_do_this  33357
#define IDS_Warning                     33358
#define IDS_Sure_want_to_set_encoder_to_zero 33359
#define IDS_Failed_to_Save              33360
#define IDS_Error                       33361
#define IDS_Failed_To_Retrieve          33362
#define IDS_Saved                       33363
#define IDS_Failed                      33364
#define IDS_Incompatible_file_type      33365
#define IDS_No_Plate_info               33366
#define IDS_No_Standard_info            33367
#define IDS_Plates_Not_Scanned          33368
#define IDS_Test_Piece_Not_Scanned      33369
#define IDS_Sure_Finish_This_Inspection_And_Save 33370
#define IDS_Saving                      33371
#define IDS_Restart_Required            33372
#define IDS_Cannot_Open_Last_Settings   33373
#define IDS_Not_DOS_Setup_File          33374
#define IDS_Protection_Ring_Tripped     33375
#define IDS_Successfully_Saved          33376
#define IDS_Not_Saved                   33377
#define IDS_Batch_Details_Empty_Scan_Not_Permitted 33378
#define IDS_File_Exists_Overwrite       33379
#define IDS_Too_Many_Views_Allocated    33380
#define IDS_Scan_Finished               33381
#define IDS_Prompt                      33382
#define IDS_Something_Wrong_Images_Not_Saved 33383
#define IDS_Wakey_Wakey                 33384
#define IDS_Unable_Display_Plate        33385
#define IDS_Unable_Display_Standard     33386
#define IDS_Scan_Halted_Not_Safe        33387
#define IDS_Change_Screen_Settings      33388
#define IDS_Cannot_Open_UlFile          33389
#define IDS_Wrong_File_Type             33390
#define IDS_Current_Water_Path_Not_Valid 33391
#define IDS_Current_Water_Path_Not_In_Error_Margin 33392
#define IDS_Unable_To_Load_DLL          33393
#define IDS_Unable_To_Retrieve_DLLRegisterServer 33394
#define IDS_Could_Not_Open_Service_Control_Manager 33395
#define IDS_No_Registry_Entry           33396
#define IDS_Registry                    33397
#define IDS_No_Printer_Drivers_Installed 33398
#define IDS_Failure                     33399
#define IDS_XT2_AXIS_DLG                33400
#define IDS_YT2_AXIS_DLG                33401
#define IDS_Z2_AXIS_DLG                 33402
#define IDS_TIMESLOT_8                  33403
#define IDS_TIMESLOT_9                  33404
#define IDS_TIMESLOT_10                 33405
#define IDS_TIMESLOT_11                 33406
#define IDS_TIMESLOT_12                 33407
#define IDS_TIMESLOT_13                 33408
#define IDS_TIMESLOT_14                 33409
#define IDS_TIMESLOT_15                 33410
#define IDS_Not_Compatible_Setup_File   33440
#define IDS_Printing_Process            33441
#define IDS_Before_End_Of_Page          33442
#define IDS_Printing_Process_Error_Start_Doc 33443
#define IDS_General_Error               33444
#define IDS_Printing_Error              33445
#define IDS_Out_Of_Memory               33446
#define IDS_User_Abort                  33447
#define IDS_Failed_To_Deallocate_Driver 33448
#define IDS_Failed_To_Allocate_Hardware_Resource 33449
#define IDS_Incorrect_Version_USL_Driver 33450
#define IDS_Mailbox_Failed              33451
#define IDS_Reset_Screen                33452
#define IDS_Plate_Size_Not_Correct      33453
#define IDS_Too_Late_Plate_Sentenced    33454
#define IDS_Switch_On_Ultrasonics_Oscilloscope 33455
#define IDS_Rf_Trace_Added              33456
#define IDS_Congratulations             33457
#define IDS_No_Traces_Stored_For_Plate  33458
#define IDS_Cannot_Save_Last_Settings   33500
#define IDS_Failed_To_Open              33501
#define IDS_Open_Error                  33502
#define IDS_Incorrect_Template_File_type 33503
#define IDS_Read_Error                  33504
#define IDS_Printer_Not_Initialise      33505
#define IDS_Could_Not_Start_Page        33506
#define IDS_Error_Loading_Library_Function 33507
#define IDS_Error_Loading_PMAC_Library  33508
#define IDS_Incorrect_Serial_Port       33510
#define IDS_MHz                         33511
#define IDS_Error_Closing_Serial_Port   33512
#define IDS_Serial_Port                 33513
#define IDS_Incorrect_Serial_Port_Number 33514
#define IDS_No_PMAC_Not_Init            33515
#define IDS_Could_Not_Init_PMAC_Comm    33516
#define IDS_Failed_To_Allocate_Hardware_Resources 33517
#define IDS_Incorrect_Version_Servo_Driver 33518
#define IDS_Failed_To_Init_PMAC_Comms_Try_Hardware_Reset 33519
#define IDS_PMAC_Failed_On_Timeout      33520
#define IDS_Error_Writing               33521
#define IDS_To_PMAC                     33522
#define IDS_Command_Not_Allowed_During_Execution 33523
#define IDS_Data_Error_Unrecognised_Command 33524
#define IDS_Command_Not_Allowed_Unless_Buffer_Open 33525
#define IDS_Buffer_In_Use               33526
#define IDS_Program_Structural_Error    33527
#define IDS_No_Room_In_Buffer           33528
#define IDS_Both_Overtravel_Limits_Set  33529
#define IDS_Previous_Move_Not_Complete  33530
#define IDS_Motor_Is_Open_Loop          33531
#define IDS_Motor_In_CS_Not_Activated   33532
#define IDS_No_Motors_In_CS             33533
#define IDS_Not_Pointing_To_Valid_Program 33534
#define IDS_Running_Improperly_Structured_Program 33535
#define IDS_Failed_To_RX_str            33536
#define IDS_Failed_To_Get_Pump_Status   33537
#define IDS_Axes_Need_To_Be_Homed       33538
#define IDS_Motor_Not_Powered           33539
#define IDS_Rising_Edge                 33540
#define IDS_Falling_Edge                33541
#define IDS_Neg_Peak                    33542
#define IDS_Pos_Peak                    33543
#define IDS_Rectifier                   33544
#define ID_RBDACMENU_COPYTOALLTS        33544
#define IDS_Envelope                    33545
#define IDS_Log                         33546
#define ID_INFORMATION_DETAILS          33546
#define IDS_Post_Filter                 33547
#define ID_INFORMATION_NOTES            33547
#define IDS_Micro_Seconds               33548
#define ID_INFORMATION_COMPONENTID      33548
#define IDS_Inches                      33549
#define ID_INFORMATION_ANOTATION        33549
#define IDS_Plate                       33550
#define ID_VIEW_IMAGE_1                 33550
#define ID_VIEW_IMAGE_2                 33551
#define IDS_TOF                         33551
#define ID_VIEW_IMAGE_3                 33552
#define IDS_Moving_To_Safe_Height       33552
#define ID_VIEW_IMAGE_4                 33553
#define IDS_Please_Wait                 33553
#define ID_VIEW_IMAGE_5                 33554
#define IDS_Origin_Find_In_Progress     33554
#define ID_VIEW_IMAGE_6                 33555
#define IDS_Axes                        33555
#define ID_VIEW_IMAGE_7                 33556
#define IDS_Pr30                        33556
#define ID_VIEW_IMAGE_8                 33557
#define IDS_Pr15                        33557
#define ID_VIEW_IMAGE_9                 33558
#define IDS_Pl15                        33558
#define IDS_Scan_Details                33559
#define IDS_Add                         33560
#define IDS_Top_Center                  33561
#define ID_PROBE_COPYDESCRIPTIONSTOALL  33562
#define IDS_Bottom_Center               33562
#define IDS_Today                       33563
#define IDS_Zoom                        33564
#define ID_BUTTON_SELECT_DEFECTS        33565
#define IDS_Full_Image                  33565
#define ID_DEFECTS_CLEARALL             33566
#define IDS_Stop_Pause                  33566
#define ID_DEFECTS_VERIFYALL            33567
#define IDS_Restart_Scan                33567
#define ID_DEFECTS_VERIFYSELECTED       33568
#define IDS_Component_Id                33568
#define IDS_Annotate                    33569
#define IDS_SelectDefects               33570
#define IDS_Too_Many_Defects            33571
#define IDS_VSMPO                       33572
#define IDS_Ultrasonic_Report           33573
#define IDS_IMMERSION_SCANNING          33574
#define ID_DEFECTS_MICROSCAN            33575
#define IDS_Customer                    33575
#define ID_FILE_VSMPOREPORTPRINT        33576
#define IDS_X_Length                    33576
#define ID_FILE_PRESET_PRINT            33576
#define IDS_Y_Length                    33577
#define ID_ANNOTION_REMOVE              33577
#define IDS_Backwall_Gain               33578
#define ID_ANNOTATION_REMOVE            33578
#define IDS_Gate_Width                  33579
#define IDS_Title                       33580
#define IDS_Ultrasonic_Result           33581
#define IDS_Stamp                       33582
#define IDS_Comments                    33583
#define IDS_Max_Mults                   33584
#define IDS_Max_Width                   33585
#define ID_MICRO_GOTOHERE               33585
#define IDS_Administration_Only         33586
#define ID_MICRO_GOTOPEEK               33586
#define IDS_Plate_No                    33587
#define ID_FILE_REPORT                  33587
#define IDS_Date                        33588
#define ID_EXAMPLES_PLATE_REPORT        33588
#define IDS_US_Test_Card                33589
#define ID_EXAMPLES_SETUPREPORT         33589
#define IDS_US_Card                     33590
#define ID_BUTTON_DELETE_DEFECTS        33590
#define IDS_Mult_No                     33591
#define ID_TEMPLATE_EDIT                33591
#define IDS_Contract_No                 33592
#define IDS_Specification               33593
#define ID_FEATURE_DELETE               33593
#define IDS_Item                        33594
#define IDS_Technique                   33595
#define ID_SELECT_DELETE                33595
#define IDS_Lot                         33596
#define ID_SELECT_MOVE                  33596
#define IDS_Alloy                       33597
#define IDS_Spot_Size                   33598
#define IDS_Diameter                    33599
#define IDS_Focal_Length                33600
#define IDS_Z_Error                     33601
#define IDS_Serial_No                   33602
#define IDS_Frequency                   33603
#define IDS_X_Pos                       33604
#define IDS_Correction                  33605
#define IDS_File_Name                   33606
#define IDS_Feature_Top                 33607
#define IDS_Feature_Left                33608
#define IDS_Feature_Bottom              33609
#define IDS_Feature_Right               33610
#define IDS_Feature_Font_Size           33611
#define IDS_Feature_Color               33612
#define IDS_Feature_Width               33613
#define IDS_Feature_Type                33614
#define IDS_Feature_Caption             33615
#define IDS_Feature_Variable            33616
#define IDS_Report_Text                 33617
#define IDS_Report_Image                33618
#define IDS_Report_Rectangle            33619
#define IDS_Report_Date                 33620
#define IDS_Report_List                 33621
#define IDS_Report_BarGraph             33622
#define IDS_Report_Data_Value           33623
#define IDS_Report_Line                 33624
#define IDS_Contract                    33625
#define IDS_Heat                        33626
#define IDS_Item_Code                   33627
#define IDS_Number_Of_Items             33628
#define IDS_Size                        33629
#define IDS_Serial_Number               33630
#define IDS_Focal_Spot_Size             33631
#define IDS_FBH_Depth                   33632
#define IDS_Amp_At_Depth_1              33633
#define IDS_Amp_At_Depth_2              33634
#define IDS_Amp_At_Depth_3              33635
#define IDS_Nominal_Gain                33636
#define IDS_Compensation_Gain           33637
#define IDS_Inspection_Gain             33638
#define ID_BUTTON_VARIABLE              33639
#define IDS_ALRO                        33639
#define ID_BUTTON_RCTANGLE_SELECTION    33640
#define IDS_Production_Facility         33640
#define ID_ULTRASONICS_PROBES           33641
#define IDS_Formula                     33641
#define ID_FBH_ADD                      33642
#define IDS_Batch_Number                33642
#define ID_FBH_DELETE                   33643
#define IDS_Ultrasonic_Spec             33643
#define ID_POPUP_SCRIBE                 33644
#define IDS_Criteria                    33644
#define ID_DEFECTS_ADD                  33645
#define IDS_Document                    33645
#define ID_BUTTON_MOVETO_SAFE           33646
#define IDS_CALIBRATION_CHECK           33646
#define ID_MOTION_SCRIBEUP              33647
#define ID_ULTRASONICS_DACSENSITIVITY_CHECKSENSITIVITY 33649
#define ID_RBDACMENU_COPYTOTS2N         33650
#define ID_DACTABLE_CLEARALL            33651
#define ID_BUTTON_HIGH_GAIN             33652
#define ID_BUTTON_LOW_GAIN              33653
#define ID_BUTTON_REMOVE_BUBBLE         33654
#define ID_MOTION_ORIGINFIND_MARKER     33658
#define ID_MOTION_ORIGINFIND_Z2         33659
#define ID_MOTION_ORIGINFIND_XTIP2      33660
#define ID_MOTION_ORIGINFIND_YTIP2      33661
#define IDS_Relative                    61204
#define IDS_Absolute                    61205
#define IDS_XPos                        61206
#define IDS_YPos                        61207
#define IDS_Amplitude                   61208
#define IDS_Depth                       61209
#define IDS_Comment                     61210
#define IDS_Logical_Combination         61211
#define IDS_Print_Russian_Title         61212
#define IDS_Print_English_Title         61213
#define IDS_Print_Report_Number         61214
#define IDS_Print_Russian_Customer      61215
#define IDS_Print_English_Customer      61216
#define IDS_Print_Russian_Contract_No   61217
#define IDS_Print_English_Contract_No   61218
#define IDS_Print_Russian_US_Specification 61219
#define IDS_Print_English_US_Specification 61220
#define IDS_Print_Russian_Item          61221
#define IDS_Print_English_Item          61222
#define IDS_Print_RussianTechnique      61223
#define IDS_Print_English_Technique     61224
#define IDS_FBH                         61225

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        255
#define _APS_NEXT_COMMAND_VALUE         33662
#define _APS_NEXT_CONTROL_VALUE         1606
#define _APS_NEXT_SYMED_VALUE           247
#endif
#endif
