//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SectorApp.rc
//
#define IDD_ABOUTBOX                    100
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_DYNAMIC                     126
#define IDR_DYNAMIC_NR                  127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ASCOPE                      129
#define IDR_SectorWeldTYPE              130
#define ID_WINDOW_MANAGER               131
#define IDR_DSCOPE_CORRECTED            132
#define IDS_EDIT_MENU                   306
#define IDR_BSCOPE                      310
#define IDR_CSCOPE                      311
#define IDR_DSCOPE                      312
#define IDR_DYNAMIC_NC                  313
#define IDD_DIALOG_ASCOPE_TOOLBAR       313
#define IDR_CSCOPE1                     314
#define IDR_DYNAMIC_CSCOPE              314
#define IDD_DIALOG_DYNAMIC_SETTING      315
#define IDD_DIALOG_ANALYSIS             316
#define IDR_HARDWARE_CSCOPE             317
#define IDC_COMBO_PROBE                 1000
#define IDC_COMBO_CYCLE                 1001
#define IDC_EDIT_CYCLE_QUANTITY_1       1001
#define IDC_COMBO_PROBE3                1002
#define IDC_COMBO_DISPLAY_MODE          1002
#define IDC_EDIT_POINT_QUANTITY_1       1002
#define IDC_EDIT_MINIMUM_ANGLE_1        1003
#define IDC_EDIT_STEP_ANGLE_1           1004
#define IDC_EDIT_CYCLE_QUANTITY_2       1005
#define IDC_EDIT_POINT_QUANTITY_2       1006
#define IDC_EDIT_MINIMUM_ANGLE_2        1007
#define IDC_EDIT_STEP_ANGLE_2           1008
#define IDC_EDIT_ENCODER_AXIS_LENGTH    1009
#define IDC_EDIT_ENCODER_AXIS_STEP      1010
#define IDC_EDIT_PIECE_THICKNESS        1011
#define IDC_EDIT_VELOCITY               1012
#define IDC_EDIT_SAMPLING_PERIOD        1013
#define IDC_RADIO_PROBE_1               1014
#define IDC_RADIO_PROBE_2               1015
#define IDC_RADIO_PROBE_3               1016
#define IDC_BUTTON_APPLY_SETTING        1017
#define IDC_BUTTON1                     1018
#define IDC_BUTTON_RESET_X_MIN          1018
#define IDC_EDIT_X_MIN                  1019
#define IDC_SPIN_X_MIN                  1020
#define IDC_EDIT_X_MAX                  1021
#define IDC_SPIN_X_MAX                  1022
#define IDC_EDIT_Y_MIN                  1023
#define IDC_SPIN_Y_MIN                  1024
#define IDC_EDIT_Y_MAX                  1025
#define IDC_SPIN_Y_MAX                  1026
#define IDC_EDIT_Z_MIN                  1027
#define IDC_SPIN_Z_MIN                  1028
#define IDC_EDIT_Z_MAX                  1029
#define IDC_SPIN_Z_MAX                  1030
#define IDC_EDIT_X_POS                  1031
#define IDC_EDIT_CURSOR_X               1031
#define IDC_SPIN_X_POS                  1032
#define IDC_EDIT_CURSOR_Z               1032
#define IDC_RADIO_BOTH_PROBE            1033
#define IDC_EDIT_Y_POS                  1034
#define IDC_SPIN_Y_POS                  1035
#define IDC_EDIT_Z_POS                  1036
#define IDC_SPIN_Z_POS                  1037
#define IDC_RADIO_GATE                  1038
#define IDC_RADIO_SLICE                 1039
#define IDC_BUTTON_RESET_X_MAX          1040
#define IDC_BUTTON_RESET_Y_MIN          1041
#define IDC_BUTTON_RESET_Y_MAX          1042
#define IDC_BUTTON_RESET_Z_MIN          1043
#define IDC_BUTTON_RESET_X_MIN6         1044
#define IDC_BUTTON_RESET_Z_MAX          1044
#define IDC_COMBO1                      1046
#define IDC_CHECK_BACKWALL_REBOUND      1047
#define IDC_STATIC_CURSOR_X             1048
#define IDC_STATIC_CURSOR_Z             1049
#define IDC_STATIC_CURSOR_UNIT_X        1050
#define IDC_STATIC_CURSOR_UNIT_Z        1051
#define ID_VIEWS_BSCOPE                 32771
#define ID_VIEWS_CSCOPE                 32772
#define ID_VIEWS_DSCOPE                 32773
#define ID_VIEWS_DYNAMICVIEW            32774
#define ID_VIEWS_DYNAMIC                32775
#define ID_VIEWS_DYNAMICNCVIEW          32776
#define ID_VIEWS_DYNAMIC_NC_VIEW        32777
#define ID_VIEWS_DYNAMIC_NC             32778
#define ID_VIEWS_ASCOPE                 32779
#define ID_FILE_SAVE32780               32780
#define ID_FILE_LOAD                    32781
#define ID_Menu                         32782
#define ID_FILE_LOADDEMOFILE            32783
#define ID_FILE_LOAD_DEMO_FILE          32784
#define ID_FILE_LOAD_DATA               32785
#define ID_FILE_SAVE_DATA               32786
#define ID_VIEWS_DYNAMICC               32787
#define ID_Menu32788                    32788
#define ID_VIEWS_DYNAMIC_CSCOPE         32789
#define ID_VIEWS_HARDWARE_CSCOPE_AMP_0  32791
#define ID_VIEWS_HARDWARE_CSCOPE_AMP_1  32792
#define ID_VIEWS_HARDWARE_CSCOPE_AMP_2  32793
#define ID_VIEWS_HARDWARE_CSCOPE_AMP_3  32794
#define ID_VIEWS_DYNAMICCSCAN           32795
#define ID_DYNAMICCSCAN_DYNAMICC        32796
#define ID_DYNAMICCSCAN_DYNAMICC32797   32797
#define ID_DYNAMICCSCAN_C               32798
#define ID_DYNAMICCSCAN_C32799          32799
#define ID_DYNAMICCSCAN_C32800          32800
#define ID_DYNAMICCSCAN_C32801          32801
#define ID_DYNAMICCSCAN_C32802          32802
#define ID_DYNAMICCSCAN_C32803          32803
#define ID_VIEWS_HARDWARE_CSCOPE_TOF_0  32804
#define ID_VIEWS_HARDWARE_CSCOPE_TOF_1  32805
#define ID_VIEWS_HARDWARE_CSCOPE_TOF_2  32806
#define ID_VIEWS_HARDWARE_CSCOPE_TOF_3  32807
#define ID_VIEWS_D                      32808
#define ID_VIEWS_DSCOPE_CORRECTED       32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
